### ISSUE TITLE
Live docs site not updated from source

### ISSUE THREAD

**Issue by chipzoller** [kube-vip/kube-vip#179]
**Documentation bug**
Appears that the page [here](https://github.com/plunder-app/kube-vip/blob/master/docs/hybrid/index.md) isn't getting updated [here](https://kube-vip.io/hybrid/). Specifically on the latter, there is a misspelling of the flag written as `--servcies`.

**Comment by thebsdbox** [comment]
Unfortunately at this time the docs aren't updated live.. they're updated when I manually trigger an update.

**Comment by onedr0p** [comment]
@thebsdbox would it make sense to use mkdocs? This is a neat project https://github.com/squidfunk/mkdocs-material

**Comment by thebsdbox** [comment]
There's a nice idea, although the docs are terrible at the moment. I've been struggling to find an opportunity for a re-write.

**Comment by thebsdbox** [comment]
We can now use Git Hub Pages for this -> https://kube-vip.github.io/kube-vip/

**Comment by onedr0p** [comment]
How are they being published? I don't see a github workflow for it.
