### ISSUE TITLE
Proxy Protocol support in kube-vip

### ISSUE THREAD

**Issue by sandys** [kube-vip/kube-vip#184]
**Is your feature request related to a problem? Please describe.**
https://github.com/k3s-io/k3s/discussions/2997#discussioncomment-449838
https://github.com/moby/moby/issues/39465
https://github.com/moby/moby/issues/25526
https://github.com/traefik/traefik-helm-chart/issues/380

Getting real client-ip is a very big issue that comes all over the place. The only real way to solve this in a scalable, standards compliant way is to inject Proxy Protocol headers 

**Describe the solution you'd like**
Proxy protocol is a fully open standard and supported by most known network servers:

- https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
- https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html
- https://cloud.google.com/load-balancing/docs/tcp/setting-up-tcp#proxy-protocol
- https://docs.openshift.com/container-platform/3.9/install_config/router/proxy_protocol.html
- https://docs.traefik.io/configuration/entrypoints/#proxyprotocol
- https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/
- https://aws.amazon.com/about-aws/whats-new/2013/07/30/elastic-load-balancing-now-supports-proxy-protocol/
- https://avinetworks.com/docs/16.3/proxy-protocol-support/
- https://blog.digitalocean.com/load-balancers-now-support-proxy-protocol/
- https://www.brightbox.com/blog/2019/03/12/proxy-protocol-load-balancer-api/
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-proxy-protocol

kube-vip should inject proxy protocol v2 headers into the requests.

**Comment by nickperry** [comment]
Kube-vip is not a proxy / load balancer - it's a control-plane component that provides VIPs. As it doesn't sit in the data path, I don't believe there's any scope for it to do anything with Proxy Protocol.

**Comment by thebsdbox** [comment]
Closing as stale, please re-open if there is a need in the future.

**Comment by Cellebyte** [comment]
@exfly kube-vip is still just Layer 4 (TCP/UDP) and relies on Kube-proxy rules for the service implementation. I don‘t get how it could inject L7 details.

**Comment by petrm** [comment]
Hi all. I was wondering if there is a solution/workaround to this problem, apart from maybe placing another proxy in front of the cluster? I only ever see in the access logs the internal cluster IP, with no way of recovering the real client address.

**Comment by Cellebyte** [comment]
This is something not related to Kube-vip but rather a kube-proxy thing. Please take a look at the kubernetes documentation for Services. `ExternalTrafficPolicy`

**Comment by petrm** [comment]
Thanks @Cellebyte for the nudge in the right direction. I was missing two things:
1) in the service externalTrafficPolicy: Local
2) and in kube-vip manifest svc_election=true to make 1) actually work

Obviously I didn't read the documentation properly, because it is all in there: https://kube-vip.io/docs/usage/kubernetes-services/#external-traffic-policy-kube-vip-v050

**Comment by thebsdbox** [comment]
Additionally this is something that we're hoping to implement in kube-gateway 👍
