### ISSUE TITLE
after delete last loadbalancer service, VIP has been deleted from all nodes

### ISSUE THREAD

**Issue by joace** [kube-vip/kube-vip#188]
**Describe the bug**
I'm not sure whether this is a bug or expected behavior by design, but want to post here for some inputs.
I created a k3s cluster with k3os image (v1.19.5-rc.1), 3 server nodes and  3 agent nodes. I wanted to use kube-vip (daemonset) for both control-plan HA and service load balance, so installed plndr-cloud-controller also. Once initial setup, CP BL worked as expected, VIP had been configured to one of server node, I could connect from remote client, even shutdown the current leader node, the VIP would move to next elected node. So far everything was good.

Then deployed a quick app and exposed http 80 service, as VIP also set in plndr-cc configmap, the service got the right external IP, I could also access it (see 1st screenshot). At the same time, CP HA still working. 

Then deleted the service (from remote client), the cmd just stuck there without returning the successful message as usual. But finally figured out it was because VIP had been removed from current node, and not moved to other nodes, so apiserver connection lost, if checked from local console, we could see last service actually deleted (2nd screenshot). But all the server nodes didn't have VIP bonded (checked with 'ip a') , even though all kube-vip DS/POD are still running correctly.

If my understanding is correct, I would expect VIP still bind to current node, since there was no node failure to make it migrated.

**To Reproduce**
1. Create a multi node k3s cluster;
2. Follow the link [here](https://kube-vip.io/control-plane/#k3s) to setup kube-vip and plndr-cc manifests to get both working as expected;
3. Deploy an app and expose http service (only non-default service with external VIP assigned); 
4. Delete this service, then issue occurs

**Expected behavior**
Since kube-vip enabled for both CP HA and service LB, even I delete all service LB, the VIP still expected working on elected node for whole cluster CP HA. 

**Screenshots**
Working screenshot before deleting service.
![image](https://user-images.githubusercontent.com/8643069/112584396-c64de700-8dc5-11eb-8a07-e45530bffebc.png)

After deleting last exposing service, all the kube-vip ds/pod still running
![image](https://user-images.githubusercontent.com/8643069/112584847-a79c2000-8dc6-11eb-9ec4-2e70dad82a72.png)

**Environment (please complete the following information):**
 - OS/Distro: k3os v1.19.5-rc.1
 - Kubernetes Version: v1.19.5+k3s1
 - Kube-vip Version: 0.3.2

**`Kube-vip.yaml`:**
>
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        creationTimestamp: null
        name: kube-vip-ds
        namespace: kube-system
      spec:
        selector:
          matchLabels:
            name: kube-vip-ds
        template:
          metadata:
            creationTimestamp: null
            labels:
              name: kube-vip-ds
          spec:
            containers:
            - args:
              - manager
              env:
              - name: vip_arp
                value: "true"
              - name: vip_leaderelection
                value: "true"
              - name: vip_leaseduration
                value: "5"
              - name: vip_renewdeadline
                value: "3"
              - name: vip_retryperiod
                value: "1"
              - name: vip_interface
                value: "eth0"
              - name: vip_address
                value: "15.115.66.33"
              - name: port
                value: "6443"
              - name: vip_cidr
                value: "32"
              - name: cp_enable
                value: "true"
              - name: cp_namespace
                value: "kube-system"
              - name: svc_enable
                value: "true"
              image: plndr/kube-vip:0.3.2
              imagePullPolicy: Always
              name: kube-vip
              resources: {}
              securityContext:
                capabilities:
                  add:
                  - NET_ADMIN
                  - SYS_TIME
              volumeMounts:
              - mountPath: /etc/kubernetes/admin.conf
                name: kubeconfig
              - mountPath: /etc/ssl/certs
                name: ca-certs
                readOnly: true
            hostNetwork: true
            serviceAccountName: kube-vip
            nodeSelector:
              node-role.kubernetes.io/master: "true"
            tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/master
            volumes:
            - hostPath:
                path: /etc/rancher/k3s/k3s.yaml
              name: kubeconfig
            - hostPath:
                path: /etc/ssl/certs
              name: ca-certs
        updateStrategy: {}

**Additional context**

1. the default servicelb / traefik in k3os have been disabled;
2. when issue occurs, the current leader node seems still broadcasting ARP update for VIP via configured iface;
3. Tried below ways to check whether VIP can be recovered:
   a. reboot the current leader node ==> VIP moved to a new node;
   b. recreate a LB service ==> VIP bond again to previous leader node;
   c. manually apply kube-vip.yaml ==> VIP not recovered;

**Comment by thebsdbox** [comment]
This should all have been addressed in the last few versions of kube-vip. This is pretty stale so I'm going to close it for now

**Comment by lubronzhan** [comment]
Looks like the external service type lb has the same IP as the kube-vip control plane IP.
Is this supported scenario?

**Comment by lubronzhan** [comment]
I verified in my testbed with kube-vip 0.4.2, kube-vip-cloud-provider 0.0.2. This issue no longer exist.
