### ISSUE TITLE
The image in the generated vip.yaml does not match with the provided in the command line

### ISSUE THREAD

**Issue by anagno** [kube-vip/kube-vip#207]
Hello Everyone,

This probably is my fault :)
When the CI is executed the name of the image in the docker hub is the name of the tag (https://github.com/kube-vip/kube-vip/blob/main/.github/workflows/release.yaml#L18). So in the case of the latest release, the automatically generated image in docker hub corresponds to plndr/kube-vip:v0.3.4. But when I use the command 

```
docker run --network host \
--rm plndr/kube-vip:v0.3.4 manifest pod \
--interface eth0 \
--address IP_ADDRESS \
--controlplane \
--arp \
--leaderElection | sudo tee /etc/kubernetes/manifests/vip.yaml
```
to generate the vip.yaml, the image in the yaml file was

```
    image: plndr/kube-vip:0.3.4
```
Notice the missing ```v``` in front of the numbers

It took me some time to find the missing v, because there was also plndr/kube-vip:0.3.4 in docker hub (which was probably pushed manually).

The simplest solution to fix this one is to tag without the ```v```. 
Alternative the line that specifies the name of the image, should filter the ```v``` from the name of the tag.

Kind regards,

Vasileios

**Comment by thebsdbox** [comment]
Fixed, and rebuilt 0.3.5 with the fix.
