### ISSUE TITLE
nodeSelector doesn't let Daemonset to schedule pods  

### ISSUE THREAD

**Issue by tahaozket** [kube-vip/kube-vip#209]
**Describe the bug**
kube-vip generated manifest file has a nodeSelector which helps to schedule pods on master nodes;

`      nodeSelector:
          node-role.kubernetes.io/master: "true"
`

But kubeadm generates master nodeSelector as without a "true" value like this; [kubeadm reference](https://github.com/kubernetes/kubeadm/blob/master/docs/design/design_v1.9.md#mark-master)

`      nodeSelector:
          node-role.kubernetes.io/master: ""
`
That's because kube-vip daemonset can't schedule pods on master nodes.

**To Reproduce**
1. Deploy a new cluster with kubeadm/kubespray
2. It automatically labels the master node without a value
3. Generate a manifest using kube-vip
4. When you apply the manifest which generated with kube-vip doesn't schedule pods

**Expected behavior**
kube-vip daemonset should schedule pods on master nodes

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 20.04
 - Kubernetes Version: v1.20.6
 - Kube-vip Version: 0.3.4

**Comment by thebsdbox** [comment]
This has been fixed !
