### ISSUE TITLE
0.3.4 not working on arm

### ISSUE THREAD

**Issue by HaveFun83** [kube-vip/kube-vip#210]
**Describe the bug**

confusing image tagging

image tag **0.3.4** only support arch amd64
and now there is an ***v0.3.4*** with multiarch support

**To Reproduce**
on arm `docker run plndr/kube-vip:0.3.4`
`standard_init_linux.go:228: exec user process caused: exec format error`

**Expected behavior**

 `docker run plndr/kube-vip:0.3.4` on arm should work like version 0.3.0 before.

**Comment by HaveFun83** [comment]
also `kube-vip manifest` is not working as it use 0.3.4

**Comment by thebsdbox** [comment]
Image tagging is fixed from 0.3.5 onwards, apologies for the confusion!
