### ISSUE TITLE
Why leader election and not true load balancing?

### ISSUE THREAD

**Issue by 205g0** [kube-vip/kube-vip#213]
This is an architectural question: Why do you have leader election with BGP? What I've understood is that you can have true load balancing with BGP unlike with ARP.[1]

[1] https://metallb.universe.tf/concepts/bgp/

**Comment by thebsdbox** [comment]
LeaderElection doesn't happen when you use BGP.

**Comment by Jean-Daniel** [comment]
Then, maybe the BGP doc shouldn't says: 

`When a node is elected as a leader then it will update it's peers so that they are aware to route traffic to that node in order to access the VIP.`

(this is in 0.1.8 change log on https://kube-vip.io/hybrid/ )
