### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by clrxbl** [kube-vip/kube-vip#215]
**Is your feature request related to a problem? Please describe.**
Currently I deploy my entire infrastructure through a Helmfile. MetalLB is causing me issues and I wouldn't mind switching over to kube-vip, but it's missing a Helm chart.

**Describe the solution you'd like**
Create & deploy a Helm chart

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by voidengineer** [comment]
Yes, please!

A Helm chart would fit much better into any IaC-driven deployment than pulling the image and calling a CLI to generate the descriptors.

**Comment by yaocw2020** [comment]
@thebsdbox I have developed a helm chart before. However, it only supports ARP mode.

https://github.com/harvester/load-balancer-harvester/tree/main/deploy/harvester-load-balancer/dependency_charts/kube-vip

I can submit the helm chart to kube-vip. We may need a new helm repo and site for users.

**Comment by thebsdbox** [comment]
@yaocw2020 This would be epic! If you can do that I can then try and do then next bits for BGP! (I've never written a helm chart before though)

**Comment by yaocw2020** [comment]
> @yaocw2020 This would be epic! If you can do that I can then try and do then next bits for BGP! (I've never written a helm chart before though)

Can you create a new repo for the helm chart? Refer to https://github.com/groundhog2k/helm-charts as an example.

**Comment by thebsdbox** [comment]
Done -> https://github.com/kube-vip/helm-charts

You should be able to clone that and add your initial chart (I think)

**Comment by thebsdbox** [comment]
Boom! 

https://kube-vip.io/helm-charts
