### ISSUE TITLE
aarch64 build

### ISSUE THREAD

**Issue by michelcve** [kube-vip/kube-vip#217]
I'm using Fedora Core OS on a bunch of Raspberry Pi's, running kubernetes.

Unfortunately there is no aarch64 build so I can't use kube-vip at the moment.

Would it be possible to add that build target?

**Comment by thebsdbox** [comment]
https://hub.docker.com/r/plndr/kube-vip/tags?page=1&ordering=last_updated 👈  images are built for ARM already.

**Comment by michelcve** [comment]
My apologies, I wasn't aware these could be used vor aarch64 target as well... I guess I have to go figure out how I can convince kubernetes to use these. Thanks.

**Comment by thebsdbox** [comment]
It should just pull the image based upon the architecture of the machine that is trying to execute the container.
