### ISSUE TITLE
How to install kube-vip to replace metallb (L2) in Kind?

### ISSUE THREAD

**Issue by Boes-man** [kube-vip/kube-vip#228]
**Is your feature request related to a problem? Please describe.**
I would like to test kube-vip to replace metallb (l2) in KIND, but can't find any installation docs. 

**Describe the solution you'd like**
Provide kubernetes manifest based installation instructions. Helm would be second choice or can be provided later.

**Describe alternatives you've considered**
Stay with Metallb and keepalived

**Additional context**
Getting started is not obvious at all.

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/kube-vip/tree/main/testing/e2e

We do it in the e2e testing.. I unfortunately didn't write it and I've (embarrassingly) never tried KIND. If that helps let me know, if not *standby* and i'll have a play with KIND 😂

**Comment by thebsdbox** [comment]
TADA -> https://kube-vip.io/usage/kind/

**Comment by Boes-man** [comment]
Thanks @thebsdbox Not working for me, as per the error below.

`Events:
  Type     Reason                   Age                From                Message
  ----     ------                   ----               ----                -------
  Warning  SyncLoadBalancerFailed   64s                service-controller  Error syncing load balancer: failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services "nginx": the object has been modified; please apply your changes to the latest version and try again
  Normal   EnsuringLoadBalancer     59s (x2 over 64s)  service-controller  Ensuring load balancer
  Warning  UnAvailableLoadBalancer  59s (x2 over 64s)  service-controller  There are no available nodes for LoadBalancer
  Normal   LoadbalancerIP           59s                service-controller  -> 172.18.100.12
  Normal   EnsuredLoadBalancer      59s                service-controller  Ensured load balancer`
