### ISSUE TITLE
remove redundant VIP when modify the vip_address in static Pod

### ISSUE THREAD

**Issue by lianghao208** [kube-vip/kube-vip#238]
When I modify the vip_address in static Pod yaml file, I notice the original vip_address still bond to the interface. It turns out 2 vip_address was bond to the same network interface. (one of them is the new vip_address, another is the original vip, which is redundant, needed to be removed) , is there a way to clean up the original vip?
![image](https://user-images.githubusercontent.com/14137033/125149910-745f8000-e16e-11eb-80b6-e996753ed2bb.png)
![image](https://user-images.githubusercontent.com/14137033/125149921-8c370400-e16e-11eb-922a-af65b8e1d415.png)

**Comment by KiddHsieh** [comment]
You can remove unwanted ip address manually with linux command: sudo ip a del REDUNDANT-VIP/32 dev eth0
