### ISSUE TITLE
Not an issue, just a thank you

### ISSUE THREAD

**Issue by kylos101** [kube-vip/kube-vip#239]
This is amazing, I just got it setup, and cannot believe it was that easy to get working!

I setup my Traefik ingress to use the kube-vip IP address as its external IP, on my bare-metal cluster at home.

Thank you, `kube-vip` team. Y'all rock!

**Comment by onedr0p** [comment]
Thanks

**Comment by jhughes2112** [comment]
Thanks!  Pretty cool system.  I've been running it for about 6 months bare metal at home.  👍

**Comment by cprivitere** [comment]
Thanks has been received.
