### ISSUE TITLE
Kube-vip doesn't work with vip port changed

### ISSUE THREAD

**Issue by KiddHsieh** [kube-vip/kube-vip#240]
**Describe the bug**
I alter kube-vip's VIP port due to my k8s controlPlaneEndpoint is 192.168.20.199:6444 by creating manifest : `docker run --network host --rm plndr/kube-vip:0.3.4 manifest pod --interface ens160 --vip 192.168.20.199 --port 6444 --lbBackEndPort 6443 --controlplane --services --arp --leaderElection | sudo tee kube-vip/kube-vip.yaml` and copy the kube-vip yaml to /etc/kubernetes/manifests/, yet I init k8s and kube-vip can't run properly. the error messages in kube-vip docker image: (get it from docker logs):
```
I0709 03:59:13.758663       1 leaderelection.go:243] attempting to acquire leader lease  kube-system/plndr-cp-lock...
I0709 03:59:13.759184       1 leaderelection.go:243] attempting to acquire leader lease kube-system/plndr-svcs-lock...
E0709 03:59:13.767019       1 leaderelection.go:325] error retrieving resource lock kube-system/plndr-svcs-lock: Get "https://kt121:6444/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-svcs-lock": dial tcp 127.0.1.1:6444: connect: connection refused
E0709 03:59:13.767192       1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kt121:6444/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 127.0.1.1:6444: connect: connection refused
```
Even I alter the yaml manually to add env setting 
```
- name: lb_backendport
  value: "6443"
```
and it still didn't work.

**Expected behavior**
kube-vip static pod can run properly and make k8s HA cluster works fine.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 18.04.5
 - Kubernetes Version: v1.19.6
 - Kube-vip Version: 0.3.4

**`Kube-vip.yaml`:**
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens160
    - name: port
      value: "6444"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.20.199
    image: plndr/kube-vip:0.3.4
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}
```

**Comment by sondercoder** [comment]
I am experiencing the same issue as well:

Environment (please complete the following information):

OS/Distro: Ubuntu 20.04.3 LTS
Kubernetes Version: v1.22.1
Kube-vip Version: 0.3.8

If I deploy kube-vip using 0.1.1 or if I dont modify the VIP Port with 0.3.8, the VIP IP will ping during deployment.

**Comment by thebsdbox** [comment]
This logic has completely changed in 0.4.x +
