### ISSUE TITLE
k3s on equinix metal docs don't describe $EIP

### ISSUE THREAD

**Issue by flokli** [kube-vip/kube-vip#241]
https://kube-vip.io/hybrid/daemonset/#k3s-overview-on-equinix-metal mentions a `export EIP=x.x.x.x`, but it's very unclear what this should point to.

Is that meant to be the (elastic) address of kube-apiserver?

As far as I understand the Equinix Metal CCM, it look it looks up the external IP via some tag, does some manual healthchecking and plans announcing it from that node.

I don't really understand what happens after that - and how kube-vip knows which ip(s) to announce from which nodes.

**Comment by flokli** [comment]
So `$EIP` /is/ actually a (previously created) elastic IP in EQXM, that's announced as a control plane IP.

**Comment by flokli** [comment]
I did some more observations - it seems the `--controlPlane` mode:

> Enables kube-vip control-plane functionality

…does try to ping whatever's on `${address}:${port}`, and if it's reachable, announce `${vip_address}` (and add the address to `${vip_interface}`.

It should probably documented how "kube-vip control-plane functionality" actually looks like.

The `port` and `vip_address` environment variables probably shouldn't be in the generated manifest, and the CLI complain if you set it, without setting `--controlPlane`?

**Comment by thebsdbox** [comment]
This documentation was all re-written a long time ago. Closing this one for now.
