### ISSUE TITLE
Workers and Master daemonsets?

### ISSUE THREAD

**Issue by flokli** [kube-vip/kube-vip#254]
**Is your feature request related to a problem? Please describe.**
I use kube-vip to both announce services and the controlplane via BGP.

I want to announce the controlplane IP from controlplane nodes only.
Other services (ideally) should only be announced from the nodes running them (see https://github.com/kube-vip/kube-vip/issues/201), and as long as that doesn't exist, from all worker nodes.

Right now I'm using the DaemonSet, which was basically generated by the following command:

```
./kube-vip manifest daemonset \
  --interface lo \
  --vip 1.1.1.1 \
  --controlplane \
  --services \
  --inCluster \
  --taint \
  --bgp \
  --annotations metal.equinix.com
```

This DaemonSet will only be scheduled on the master node(s), as the `--taint` also creates a `nodeSelector`. If you have a single master, you loose all other `LoadBalancer` services too.

I tried removing the `nodeSelector`, and pods got scheduled on other nodes, but worker nodes complained with ` retrywatcher.go:130] "Watch failed" err="Get \"https://worker-0:6443/api/v1/nodes…` every second, and didn't announce the other services either.

I tried having one DaemonSet (with `--taint`, `--vip` and `--controlplane`, but not `--services`) on the controlplane, and another one on (other) nodes, but ran into "binding to the same port" issues, as now two bgp daemons wanted to occupy the same port.

**Describe the solution you'd like**
Ideally, I'd like to use one DaemonSet across all nodes, and `kube-vip` to be a bit smarter and only do the controlplane polling logic on control plane nodes.

**Describe alternatives you've considered**
See above.

**Comment by thebsdbox** [comment]
Apologies, I keep making incremental updates to the docs to try and make them clearer.

**Comment by osirisstar-hub** [comment]
> There seem to be some docs at https://metal.equinix.com/developers/guides/kubernetes-with-kubeadm/ - with some of the invocations there, I was able to get two different DaemonSet specs.
> 
> In combination with ensuring the control plane nodes have taints to prevent the "service daemonset" from also getting scheduled on control plane nodes I got it to work.
> 
> I feel like the kube-vip docs should be extended a lot, and/or merged with the link above.

What was your resulting daemonset yaml for the service that runs only on workers?

**Comment by flokli** [comment]
> What was your resulting daemonset yaml for the service that runs only on workers?

The controlplane nodes had some taints that the "regular" kube-vip daemonsets didn't tolerate.

**Comment by thebsdbox** [comment]
Closing this here, all documentation is being handled here -> https://github.com/kube-vip/website

If there is something specific you require, then either request it here or create a PR with your changes :)

**Comment by flokli** [comment]
That's been 4 years ago, I don't have the config or cluster anymore, sorry.
