### ISSUE TITLE
Add issue label for provider:EquinixMetal

### ISSUE THREAD

**Issue by displague** [kube-vip/kube-vip#257]
**Is your feature request related to a problem? Please describe.**
It should be easy to identify issues specific to a single provider.

**Describe the solution you'd like**
* Add a label called: `provider:EquinixMetal` (this matches the pattern of `type:LoadBalancer`)
* label existing EM issues

**Describe alternatives you've considered**
_none_

**Additional context**
_none_

**Comment by thebsdbox** [comment]
Added !
