### ISSUE TITLE
Add missing environment variable options to docs

### ISSUE THREAD

**Issue by enkelprifti98** [kube-vip/kube-vip#259]
**Is your feature request related to a problem? Please describe.**

The following environment variables seem to be missing from the docs here:

https://kube-vip.io/flags/#environment-variables

```
        - name: vip_configmap
          value: "plndr" 

        - name: vip_loglevel
          value: "5"
```

I'm not sure if `vip_configmap` does anything but `vip_loglevel` definitely provides more detailed logs which is helpful when troubleshooting.

**Describe the solution you'd like**

Add the missing environment variables listed above to the docs and any other ones that I might be missing.

**Describe alternatives you've considered**

None.

**Additional context**

I found those missing environment variable options here:

https://kube-vip.io/kubernetes/bgp/#editing-kube-vip-configuration

**Comment by thebsdbox** [comment]
Now added to the documentation ! 

Thanks for the catch !
