### ISSUE TITLE
Dual-Stack VIP

### ISSUE THREAD

**Issue by mrjester888** [kube-vip/kube-vip#269]
I am trying to setup kube-vip as dual-stack.  I've attempted to run a second instance of Kube-vip by duplicating the yaml and adjusting all of the names to kube-vip6-ds and setting the address to an IPv6 address.  The containers will not start due to this error in the pods.
`msg="listen:listen tcp :2112: bind: address already in use\n"
`
I see the port in use as `*:2112` which indicates to me that the process binds on v4 for some internal communications.  Would it be possible to have that process listen on a tcp6 socket when it detects an IPv6 address?  

Alternatively, simply allow there to be both a v4 and v6 address assigned at the same time.

**Comment by MikeZappa87** [comment]
That is the Prometheus server. We setup two instances of kube-vip and made sure to change the port from 2112 to something else. That allows you to run several instances

**Comment by mrjester888** [comment]
@MikeZappa87 Thanks for the tip. 
I am going to leave this open, because I think it should still be easier than having to build two instances.

**Comment by mrjester888** [comment]
@MikeZappa87 I started looking into how to adjust the promethus port, but am not finding the flag/env var.  How did you change it?

**Comment by MikeZappa87** [comment]
Below is the avaliable commands. 

Usage:
  kube-vip [command]
Available Commands:
  help        Help about any command
  kubeadm     Kubeadm functions
  manager     Start the kube-vip manager
  manifest    Manifest functions
  sample      Generate a Sample configuration
  service     Start the Virtual IP / Load balancer as a service within a Kubernetes cluster
  start       Start the Virtual IP / Load balancer
  version     Version and Release information about the Kubernetes Virtual IP Server
Flags:
      --addPeersToLB                  Add raft peers to the load-balancer (default true)
      --address string                an address (IP or DNS name) to use as a VIP
      --annotations string            Set Node annotations prefix for parsing
      --arp                           Enable Arp for Vip changes
      --bgp                           This will enable BGP support within kube-vip
      --bgpRouterID string            The routerID for the bgp server
      --bgppeers strings              Comma seperated BGP Peer, format: address:as:password:multihop
      --cidr string                   The CIDR range for the virtual IP address (default "32")
      --controlplane                  Enable HA for control plane, hybrid mode
      --ddns                          use Dynamic DNS + DHCP to allocate VIP for address
  -h, --help                          help for kube-vip
      --interface string              Name of the interface to bind to
      --lbBackEndPort int             A port that all backends may be using (optional) (default 6444)
      --lbBindToVip                   Bind example load balancer to VIP (default true)
      --lbEnable                      Enable a load-balancer on the VIP
      --lbName string                 The name of a load balancer instance (default "Kubeadm Load Balancer")
      --lbPort int                    Port that load balancer will expose on (default 6443)
      --lbType string                 Type of load balancer instance (TCP/HTTP) (default "tcp")
      --leaderElection                Use the Kubernetes leader election mechanism for clustering
      --leaseDuration int             Length of time a Kubernetes leader lease can be held for (default 5)
      --leaseRenewDuration int        Length of time a Kubernetes leader can attempt to renew its lease (default 3)
      --leaseRetry int                Number of times the host will retry to hold a lease (default 1)
      --localAS uint32                The local AS number for the bgp server (default 65000)
      --log uint32                    Set the level of logging (default 4)
      --metal                         This will use the Equinix Metal API (requires the token ENV) to update the EIP <-> VIP
      --metalKey string               The API token for authenticating with the Equinix Metal API
      --metalProject string           The name of project already created within Equinix Metal
      --metalProjectID string         The ID of project already created within Equinix Metal
      --multihop                      This will enable BGP multihop support
  -n, --namespace string              The configuration map defined within the cluster (default "kube-system")
      --peerAS uint32                 The AS number for a BGP peer (default 65000)
      --peerAddress string            The address of a BGP peer
      --peerPass string               The md5 password for a BGP peer
      --port int                      listen port for the VIP (default 6443)
      --promethuesHTTPServer string   Host and port used to expose Promethues metrics via an HTTP server (default ":2112")
      --provider-config string        The path to a provider configuration
      --services                      Enable Kubernetes services, hybrid mode
      --sourceIF string               The source interface for bgp peering (not to be used with sourceIP)
      --sourceIP string               The source address for bgp peering (not to be used with sourceIF)
      --startAsLeader                 Start this instance as the cluster leader
      --vip string                    The Virtual IP address


In the pod yaml: 
      containers:
      - args:
        - manager
        - --promethuesHTTPServer=:{PortGoesHere}  

You probably could set it up with --promethuesHTTPServer={IpAddress:Port} as well

**Comment by mrjester888** [comment]
Thank you very much.  Worked like a champ.  i really appreciate your help with this.

**Comment by displague** [comment]
Worth comparing notes:

https://github.com/metallb/metallb/issues/698
https://github.com/metallb/metallb/pulls/1065

**Comment by thebsdbox** [comment]
Can this be closed or would it make sense to add some docs to -> https://github.com/kube-vip/website

**Comment by MikeZappa87** [comment]
> Can this be closed or would it make sense to add some docs to -> https://github.com/kube-vip/website

It probably would make sense to be added to the docs to prevent further issues from being opened, once complete this issue should be closed?

**Comment by MikeZappa87** [comment]
> Can this really considered solved? Sounds more like a workaround.
> If the only thing preventing us from using dual-stack vip is the prometheus port, is it possible to add --disable-prometheus instead?

That is a good point, the code change looks minimal

**Comment by thebsdbox** [comment]
Yeah can do that..

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/kube-vip/pull/417

**Comment by thebsdbox** [comment]
Prometheus port can either be changed or disabled.
