### ISSUE TITLE
kube-vip uses hostname when querying API server on local host instead of using localhost

### ISSUE THREAD

**Issue by oskapt** [kube-vip/kube-vip#270]
**Describe the bug**

You can see this in the last 10 minutes of [the live stream that I did on Rancher 2.6](https://www.youtube.com/watch?v=bpc-z1GMivA). I deployed one master node of an RKE2 cluster from within Rancher, deployed kube-vip, and then deployed the other two from within Rancher. 

I deployed `demo-d` with tls-san information that included `demo-d` as a valid host. kube-vip deployed fine because it connected to `demo-d` as the API server, and the certificate matched.

When I deployed `demo-e` and `demo-f` kube-vip was unable to connect to the api server because those names weren't in the certificate. 

Can we change the Pods to query `localhost` instead?

**Comment by thebsdbox** [comment]
So here (https://github.com/kube-vip/kube-vip/blob/ab19d4a4a4c1752123ef9bbe9ae7f7117414ab42/pkg/manager/manager.go#L118) is the line that sets to hostname.

**Comment by thebsdbox** [comment]
Apologies for the delay in getting round to this.. turns out using localhost directly wouldn't work.. Notes are #285
