### ISSUE TITLE
[Feature] Support default VIP interface.

### ISSUE THREAD

**Issue by yaocw2020** [kube-vip/kube-vip#273]
**Is your feature request related to a problem? Please describe.**

Kube-vip is generally deployed as a daemonset in the Kubernetes that means all of the pods in different nodes have the same configuration and all the nodes should have the same network interface. That is a big limitation.

Kube-vip should support the default VIP interface got from the default route on the machine.

**Describe the solution you'd like**

Support the default VIP interface got from the default route on the machine

**Describe alternatives you've considered**

**Additional context**

**Comment by thebsdbox** [comment]
I think an `--autoInterface` / `vip_autointerface` flag/env should be simple enough to implement.

**Comment by venkatnsrinivasan** [comment]
@thebsdbox  Thanks for adding this. Can this added to the start command as well ? Currently it seems to be supported only for the 'manager' ?

**Comment by thebsdbox** [comment]
This was fixed a long time ago.

**Comment by QuinnBast** [comment]
> This was fixed a long time ago.

@thebsdbox Can you elaborate? How do we configure the Daemonset to use the default network? Does the environment variable need to be set? I'm in a situation where I have 3 controllers but only 2 share the network interface name.

```
            - name: vip_interface
              value: ens3
```
