### ISSUE TITLE
Adding default toleration for control-plane to helm chart

### ISSUE THREAD

**Issue by FruityWelsh** [kube-vip/kube-vip#275]
Since k8s version 1.20 the ```node-role.kubernetes.io/master``` node label has been deprecated for the node label ```node-role.kubernetes.io/control-plane```[[label rename citation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint)]. This means that the default on new clusters could fail (such as on [rke2](https://github.com/rancher/rke2/issues/1826)).

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/helm-charts/pull/7 <- tracking here !
