### ISSUE TITLE
Dual Stack IPv4/IPv6 Configuration

### ISSUE THREAD

**Issue by jjschwarz** [kube-vip/kube-vip#279]
**Describe the bug**
If the address used in the YAML as the VIP address is a dual stack address (k8s.breepriv.lothlorien.net as an example) then the outcome is random.  What is the proper method to setup kube-vip as a VIP listener for both stacks?  I have tried the documentation, but it seems a bit vague on the matter.

**To Reproduce**

Use the setup command:
sudo docker run --network host --rm plndr/kube-vip:v0.3.8 manifest pod \
--interface ens192 \
--address k8s.breepriv.lothlorien.net \
--namespace kube-vip6 \
--arp \
--leaderElection | sudo tee /etc/kubernetes/manifests/vip.yaml

Which produces the correct output.  The resulting configuration seems to cause the VIP to respond on IPv6 only.

**Expected behavior**
VIP would respond on both IPv4 and IPv6

**Environment (please complete the following information):**
 - OS/Distro: Fedora Core 7.9
 - Kubernetes Version: v1.21.5
 - Kube-vip Version: v0.3.9

**`Kube-vip.yaml`:**
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens192
    - name: vip_leaderelection
       value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: k8s.breepriv.lothlorien.net
    image: plndr/kube-vip:v0.3.8
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
       name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
status: {}

**Comment by jjschwarz** [comment]
Also testing in this configuration with a dual stack service on static IP addresses such as:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: commission-correction-form
  name: commission-correction-form-v4
  namespace: commission-correction-form
spec:
  ipFamilyPolicy: PreferDualStack
  type: LoadBalancer
  loadBalancerIP: 192.168.254.30
  ports:
    - name: "http"
      port: 443
      targetPort: 443
  selector:
    app: commission-correction-form
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: commission-correction-form
  name: commission-correction-form-v6
  namespace: commission-correction-form
spec:
  ipFamilyPolicy: PreferDualStack
  type: LoadBalancer
  loadBalancerIP: 2620:128:2000:254::30
  ports:
    - name: "http"
      port: 443
      targetPort: 443
  selector:
    app: commission-correction-form
status:
  loadBalancer: {}
---

I find that it comes up just fine...however after an intentional fail (reboot) of the leader the IPv4 service fails over to the new leader just fine, but the IPv6 service never comes back (both the IPv4 and IPv6 for the cluster migrate fine).

I see the following in the logs:
time="2021-10-06T15:47:34Z" level=info msg="Broadcasting NDP update for 2620:128:2000:254::30 (00:50:56:95:e5:55) via ens192"
time="2021-10-06T15:47:34Z" level=info msg="ndp: &{false false true 2620:128:2000:254::30 [0xc00034c340]}"

And the ip neighbor tables never show the IPv6 address again.

**Comment by displague** [comment]
Is this a duplicate of #269?

**Comment by jjschwarz** [comment]
I do not believe so, because I already referenced that article to get it setup.  It is actually is working (see my follow up post) initially,
but then failovers between hosts on IPv6  seem not  to work and we have persistent errors about failed to update lock in the logs.

**Comment by jjschwarz** [comment]
Testing this on v0.4.4 again and I am able to bring up the nodes with IPv4 and IPv6 dual stack per the information above.  I did generate a new set of manifests to make sure I was using the latest version of everything.  I am not using the service load balancer. 

I am still seeing this in the log (not sure if it is important) on the IPv6 side:

E0713 17:02:15.211343       1 leaderelection.go:367] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "plndr-cp-lock": the object has been modified; please apply your changes to the latest version and try again

After the initial update to v0.4.4 my k8s-2 node was master for both IPv4 and IPv6 correctly.  I then drained that node and rebooted it.  It seems now on v0.4.4 both the IPv4 and IPv6 addresses did move correctly to the same node.

Is the message above about leader election anything to worry about?

**Comment by thebsdbox** [comment]
In most cases leaderElections will just happen first time, sometimes the election can bounce and you'll get an error followed by a retry.

**Comment by jjschwarz** [comment]
I am seeing that error constantly in the logs after the elections...it seems that having both an IPv4 and IPv6 copy running at once is the cause.

**Comment by thebsdbox** [comment]
Ah! I bet I know what is happening! Both allocations are causing a leaderElection vote each. We're overloading the election! This is a bug 😔

**Comment by jjschwarz** [comment]
OK, it seems to be functioning for dual stack and they are ending up on the same host, but it does seem to fight a lot.

Anything I can do to assist in the debug and fix?

**Comment by jjschwarz** [comment]
Actually, I take back the "seems to be functioning".  After a period of time running both the entire cluster became unstable.  Once I turned off the IPv6 secondary setup it went back to normal.

**Comment by jjschwarz** [comment]
Is the method I used above still the best way to handle the dual stack setup or does v0.5.0 have another method to setup the dual stack control plane VIP?

**Comment by thebsdbox** [comment]
The problem here is a bunch of nodes fighting between `plndr-cp-lock` whilst one is trying to do IPv4 and the other IPv6 and the healthchecks realising that something isn't right causing more leader Elections.

**Comment by jjschwarz** [comment]
So would moving the IPv4 and IPv6 pods into separate namespaces help that at all?

**Comment by thebsdbox** [comment]
Good point, that might stop the lease collision. I can't remember (and I don't have the code open) but I think the namespaces flag is for leases.

**Comment by jjschwarz** [comment]
When you have a chance to review let me know if I should try that.

**Comment by jjschwarz** [comment]
Any updates that might have affected this situation?

**Comment by thebsdbox** [comment]
Yes, I implemented the namespaces to handle this. I'll get the documentation updated!

**Comment by jjschwarz** [comment]
OK, so jump to the latest build to resolve the issue hopefully?

**Comment by jjschwarz** [comment]
OK, so I need to put each IP stack in a separate namespace now?

**Comment by jjschwarz** [comment]
Retested on v0.5.12 and everything seems to behave

**Comment by lubronzhan** [comment]
Hi @jjschwarz when you set two IPs for apiserver, the certificate for apiserver needs to signed with both IP addresses I assume? did you use kubeadm to bootstrap k8s cluster? I think kubeadm only accepts 1 IP for control plane IP https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/. I assume you use something else?
Thank you

**Comment by jjschwarz** [comment]
I have always just used a host name that has both the A and AAAA record for the value of control-plane-endpoint.

**Comment by joggienl** [comment]
Hello here, I don't believe documentation has been updated on how to do dual stack with kube-vip for the control plane?
I'm trying to figure out whether I should use a dual-stack domain name or if I should deploy kube-vip twice (apparently in separate namespaces).
