### ISSUE TITLE
Document migration from "start" to "manager"

### ISSUE THREAD

**Issue by MaxRink** [kube-vip/kube-vip#280]
**Is your feature request related to a problem? Please describe.**
Iirc the leader election flag changed when using "manager" and newer features arent implemented by "start"
**Describe the solution you'd like**
Document the migration process to "manager"

**Comment by thebsdbox** [comment]
`start` is about to be completely removed.

**Comment by thebsdbox** [comment]
This is an old conversation, please feel free to re-open or create a new issue if needed.
