### ISSUE TITLE
Uses hostIP and environment variables to determine BGP peers

### ISSUE THREAD

**Issue by yastij** [kube-vip/kube-vip#281]
during some work with one of our users, @mtritabaugh came up with https://github.com/mtritabaugh/rack-detect which uses the host IP and some environment variables such as network CIDRs to determine BGP_PEERS and BGP_AS. I think having kube-vip supporting this natively would be useful.

cc @thebsdbox @detiber

**Comment by thebsdbox** [comment]
oooo, looks good! We kinda implemented something similar for Equinix Metal and it's cloud provider.

**Comment by thebsdbox** [comment]
Old issue, closing. (please re-open if this is still a problem)
