### ISSUE TITLE
kube-vip restarting due to losing leader election 

### ISSUE THREAD

**Issue by pradipd** [kube-vip/kube-vip#282]
**Describe the bug**
Note: that this may not be a bug per se.  Perhaps it is just a configuration problem.

We are running into situations where kube-vip is restarting because it can't retrieve the plndr-cp-lock.  This is most likely due to etcd running on hard drives that are either too slow or are hitting a temporary burst in high disk i/o. 

From the kube-vip logs we can see a timeout trying to retrieve kube-system/plndr-cp-lock
```
E1006 01:12:52.488031       1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://229d478ae6c0d7d4b9ee3bceee2f1d95e18b9e59caebd-control-plane-0:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": context deadline exceeded
I1006 01:12:52.488123       1 leaderelection.go:278] failed to renew lease kube-system/plndr-cp-lock: timed out waiting for the condition
E1006 01:12:52.488214       1 leaderelection.go:298] Failed to release lock: resource name may not be empty
time="2021-10-06T01:12:52Z" level=info msg="This node is becoming a follower within the cluster"
time="2021-10-06T01:12:52Z" level=fatal msg="lost leadership, restarting kube-vip"
```
And looking in the etcd logs we can see:
```
2021-10-02 07:57:52.692494 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/plndr-cp-lock\" " with result "error:context canceled" took too long (2.997729833s) to execute
2021-10-02 17:02:49.772965 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/plndr-cp-lock\" " with result "range_response_count:1 size:497" took too long (1.594059431s) to execute
2021-10-03 05:07:20.165179 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/plndr-cp-lock\" " with result "range_response_count:1 size:498" took too long (277.102319ms) to execute
2021-10-03 05:07:46.788421 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/plndr-cp-lock\" " with result "range_response_count:1 size:498" took too long (127.306017ms) to execute
```
From the etcd documentation (https://etcd.io/docs/v3.5/op-guide/hardware/#disks) it looks like the disk latency is too high.

The problem is that once we hit this burst, kube-vip constantly restarts.  And because of k8s restart policy, the time between restarts increases.  This makes the api-server unavailable for a long time.

**To Reproduce**
unsure.  1 reliable way to run on a HDD :).  but that seems like cheating.
Seriously, we hit this intermittently running on CSV's (https://docs.microsoft.com/en-us/windows-server/failover-clustering/failover-cluster-csvs).  My guess is that there is a temporary burst of high disk activity that causes high disk i/o latency.

**Expected behavior**
Either:
1.kube-vip doesn't restart
2.if kube-vip does restart, it can restart immediately.

**Environment (please complete the following information):**
 - OS/Distro: mariner (https://github.com/microsoft/CBL-Mariner)
 - Kubernetes Version: 1.20.7
 - Kube-vip Version: 0.3.4

**`Kube-vip.yaml`:**
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: eth0
    - name: vip_address
      value: 172.16.255.0
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    image: plndr/kube-vip:0.3.4
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
    - mountPath: /etc/ssl/certs
      name: ca-certs
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
  - hostPath:
      path: /etc/ssl/certs
    name: ca-certs
```
**Additional context**
1.Are there some flags we can tweak here to make kube-vip less sensitive to etcd issues.
2.Are there some flags we can set on pod to make kube-vip POD critical and have k8s restart the POD immediately instead of exponentially backing off?

Thanks you!

**Comment by thebsdbox** [comment]
haha, yeah this is an etcd <--> API server issue. 

There are flags to allow longer time outs with the leaderElection -> https://kube-vip.io/flags/

**Comment by pradipd** [comment]
OK. Thanks for the info. What about the first question?
If we bump up the renew deadline to say 5 or 10 s, will that effect failover time?

**Comment by Mtze** [comment]
I also ran into this problem. (Also caused by disk latency, as my test VMs are stored in a ceph cluster). 

After the failed leader election, kube-vip restarts the current leader - After some time another pod starts arping for the IP. However, the API is still not reachable over the vip:
```
he connection to the server k8s-control-plane.local:6443 was refused - did you specify the right host or port?
```
The address can be reached with `ping`.

I restarted all kub-vip pods - The API is still unreachable. 

Any ideas/hints how to resolve that? 
Thanks in advance!

**Comment by pradipd** [comment]
@thebsdbox  We changed the leaseduration, renewdeadline, and retryperiod to the ones mentioned in k8s leaderelection https://github.com/kubernetes/client-go/blob/v0.24.1/tools/leaderelection/leaderelection.go#L112.
And we have seen this issue a lot less frequently and haven't noticed any side effects.

**Comment by Mtze** [comment]
@thebsdbox It is resolved - It was a config error on my side. I misconfigured the taints... The control plane vip got rescheduled to a worker node and the API became unreachable.
