### ISSUE TITLE
Service external-ip always pending

### ISSUE THREAD

**Issue by stevesloka** [kube-vip/kube-vip#286]
**Describe the bug**
I am deploying kube-vip into a kind cluster on a OSX environment. Just trying to get my `hello-world` started. After following the Kind guide (https://kube-vip.io/usage/kind/), everything spins up correctly without errors. 

However, when I create a service `type=LoadBalancer`, kube-vip fails to write that status back to the k8s service:

```bash
I1014 15:59:55.983977       1 loadBalancer.go:229] No cidr config for namespace [default] exists in key [cidr-default] configmap [kubevip]
I1014 15:59:55.983992       1 loadBalancer.go:232] No global cidr config exists [cidr-global]
I1014 15:59:55.984007       1 loadBalancer.go:251] No range config for namespace [default] exists in key [range-default] configmap [kubevip]
I1014 15:59:55.984017       1 loadBalancer.go:256] Taking address from [range-global] pool
I1014 15:59:55.984033       1 loadBalancer.go:190] Updating service [nginx], with load balancer IPAM address [172.18.100.12]
E1014 15:59:55.995901       1 controller.go:275] error processing service default/nginx (will retry): failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services "nginx": the object has been modified; please apply your changes to the latest version and try again
I1014 15:59:55.996486       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: Error updating Service Spec [nginx] : Operation cannot be fulfilled on services \"nginx\": the object has been modified; please apply your changes to the latest version and try again"
I1014 16:00:00.997115       1 event.go:291] "Event occurred" object="default/nginx" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
```

I looked at https://github.com/kube-vip/kube-vip/issues/221 but was not able to resolve my issue looking at that thread.

**To Reproduce**
1. Follow guide: https://kube-vip.io/usage/kind/
2. kubectl apply -f https://k8s.io/examples/application/deployment.yaml
3. kubectl expose deployment nginx-deployment --port=80 --type=LoadBalancer --name=nginx

**Screenshots**
![image](https://user-images.githubusercontent.com/1048184/137355428-f539b44a-087d-45c2-9ec5-d452471a92f9.png)

**Environment (please complete the following information):**
 - OS/Distro: OSX
 - Kubernetes Version: v1.21
 - Kube-vip Version: 0.3.9 & main

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

**Comment by thebsdbox** [comment]
Fixed in new release

**Comment by sungureanu** [comment]
> This might be my problem: [kube-vip/kube-vip-cloud-provider#8](https://github.com/kube-vip/kube-vip-cloud-provider/issues/8)

The link is not working.
