### ISSUE TITLE
How to implement vip load balance？

### ISSUE THREAD

**Issue by njfanxun** [kube-vip/kube-vip#293]
3 control plane： 
170.18.9.101 
170.18.9.102 
170.18.9.103
vip：
170.18.9.100
kube-vip daemonset run ok in my k8s cluster.
so,in k8s cluster, i run three of  "whoami" images pods in worker nodes ,and create "whoami" service with loadbalance type,and loadbalanceIP is 170.18.9.100, expose 80 port。 
but i use chrome visit http://170.18.9.100，only response one node data，kube-vip no loadbalance for this service。
Is there a problem with my usage? and How to configure？

**Comment by vivekskrishna** [comment]
can you paste your service yaml definition below.

**Comment by thebsdbox** [comment]
Closing this as it's been two months.
