### ISSUE TITLE
Typo in docs -- kube-vip image tag should be v0.3.7 and not 0.3.7

### ISSUE THREAD

**Issue by wbrefvem** [kube-vip/kube-vip#299]
**Describe the bug**
There's a typo in the docs that gives the wrong image tag for kube-vip image.

**To Reproduce**
1. Go to https://kube-vip.io/hybrid/static/
2. Try to run `docker run --network host --rm ghcr.io/kube-vip/kube-vip:0.3.7`
3. Throws a "manifest unknown error"

**Expected behavior**
Docker should run the image.

**Additional context**
The correct tag appears to be `v0.3.7` and not `0.3.7`.

**Comment by thebsdbox** [comment]
Fixed in new release.
