### ISSUE TITLE
Outdated doc file `kubernetes-control-plane`

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [kube-vip/kube-vip#307]
I have noticed that in the `0.4.0` release, https://github.com/kube-vip/kube-vip/blob/v0.4.0/kubernetes-control-plane.md is the only document you didn't modify. That file contains reference to `sample config` command which is not used in any other documentation. Moreover, it still uses `0.3.7` as the target version and `1.17` as the k8s version. 

Can you confirm if that file is outdated? 

The "static" docs mention that the manifest can be generated directly from the command like. Is that the preferred method instead of generating a "config" file first?

**Comment by thebsdbox** [comment]
Yeah, this is some old documentation that isn't reference anywhere on kube-vip.io.

**Comment by SayakMukhopadhyay** [comment]
Just wanted to update that I didn't need to follow anything in that document and was still able to get my cluster up and running.

**Comment by thebsdbox** [comment]
Going to re-open this so I have a record to remove the old docs !

**Comment by thebsdbox** [comment]
This has been removed ! :D
