### ISSUE TITLE
Ability to disable laodbalancer feature on k8s service level

### ISSUE THREAD

**Issue by vivekskrishna** [kube-vip/kube-vip#310]
**Is your feature request related to a problem? Please describe.**
Right now since the kube-vip enables laodbalancing service on cluster level, we cannot have another Lb service working with kube-vip when we need different ones for services in same namespace

**Describe the solution you'd like**
Have an annotation in k8s service object which can disable loadbalancer service from kube-vip 

**Describe alternatives you've considered**
we can do it on a per namespace basis if the Container function design allows it.

**Comment by thebsdbox** [comment]
Implemented in #291 needs adding to docs.

**Comment by vivekskrishna** [comment]
@thebsdbox , nice. thank you. missed that during search. i will close this request.
