### ISSUE TITLE
Merge RBAC-related resources in with DaemonSet manifest generation

### ISSUE THREAD

**Issue by chipzoller** [kube-vip/kube-vip#314]
**Is your feature request related to a problem? Please describe.**
As of kube-vip 0.4.0, if a user wishes to run under a solution like K3s which requires running as a DaemonSet, there is a two-step process to do so. First, the RBAC resources need to be applied separately by grabbing a manifest at https://kube-vip.io/manifests/rbac.yaml; second, the user needs to select the kube-vip operating mode (ARP or BGP) and generate a DaemonSet manifest with the appropriate flags. This seems to add more work when the two are so tightly coupled.

**Describe the solution you'd like**
Augment the kube-vip DaemonSet manifes generation logic to also output the RBAC resources needed. The added benefit is, should those permissions change, they are contained in the image logic and don't depend on someone manually updating them in a separate file.

**Comment by franboccalatte** [comment]
Hi, I am following the install steps to setup a HA K3s cluster on this page [Step 3: Generate a kube-vip DaemonSet Manifest](https://kube-vip.io/docs/usage/k3s/#step-3-generate-a-kube-vip-daemonset-manifest), but the [DaemonSet manifest generation documentation](https://kube-vip.io/install_daemonset/#generating-a-manifest) link is broken showing a 404. Could you please help me to get information on how to generate that Daemonset? Thanks

**Comment by joejulian** [comment]
I would just use the [helm chart](https://github.com/kube-vip/helm-charts) that handles all that for you.
