### ISSUE TITLE
DasmonSet（--bgpRouterID、bgp_routerinterface）

### ISSUE THREAD

**Issue by xzxiaoshan** [kube-vip/kube-vip#331]
If "bgp_routerinterface" is used in the daemonset in the document, the parameter "--bgpRouterID" should not be set, right?

**Comment by xzxiaoshan** [comment]
https://kube-vip.io/install_daemonset/#bgp-example-for-daemonset

**Comment by thebsdbox** [comment]
It shouldn't need setting no, the information will probably be overwritten.

**Comment by xzxiaoshan** [comment]
ok，3Q~
Should a description be added to the document?

**Comment by MikeZappa87** [comment]
BGP requires a Router ID and AS otherwise it doesn't work

**Comment by thebsdbox** [comment]
This has been updated in the documentation.
