### ISSUE TITLE
Re-evaluate and document required Linux capabilities

### ISSUE THREAD

**Issue by mrueg** [kube-vip/kube-vip#335]
**Is your feature request related to a problem? Please describe.**
Currently, kube-vip requires the following capabilities:

```
NET_ADMIN
NET_RAW
SYS_TIME
```
As a user I'm interested in reducing capabilities to a minimum to increase the security of my systems.

**Describe the solution you'd like**
Have required capabilities documented, so users can see why and for which reason they are needed. 

**Describe alternatives you've considered**
None

**Additional context**
It seems like SYS_TIME was introduced in the beginning of this project. I might miss something here and currently don't understand why it is needed for kube-vip to function.
```
       CAP_SYS_TIME
              Set system clock (settimeofday(2), stime(2), adjtimex(2));
              set real-time (hardware) clock.
```
Introduced in: https://github.com/kube-vip/kube-vip/commit/9258e3e20565615aff2f4c14e4a08648ee647c11

**Comment by thebsdbox** [comment]
This must have been something related to RAFT which we removed recently.. we can certainly remove `SYS_TIME` if it is irrelevant.
