### ISSUE TITLE
svc_enable=>false in hybrid mode is not working as expected!

### ISSUE THREAD

**Issue by mahantsucf** [kube-vip/kube-vip#353]
**Describe the bug**

**svc_enable=>false** in hybrid mode is not working as expected!

**To Reproduce**

Deploy kube-vip by setting svc_enable is false in hybrid mode as daemon set

      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: ens192
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        **- name: svc_enable
          value: "false"**

**Expected behavior**

After deploying kube-vip, It should only works for contolplane by using vip address & It should not assign/allocate external IP address whenever we create service type: Load Balancer.

**Current behavior**

Assigning/allocating IP address of workers nodes!

**Comment by mahantsucf** [comment]
There was no response in slack, I think no one tried before!

**Comment by thebsdbox** [comment]
Can you retrieve the logs from the kube-vip pods?

**Comment by mahantsucf** [comment]
This can be closed, Issue was not related to kube-vip. We suppose to disable servicelb while installing k3s.
