### ISSUE TITLE
Additional underscore

### ISSUE THREAD

**Issue by thebsdbox** [kube-vip/kube-vip#355]
Somehow an additional underscore has been added in the environment variable, this will need restoring to match expected behaviour.

https://github.com/kube-vip/kube-vip/blob/c5049407c7c536c6c011684e4cd6b2c2087205cb/pkg/kubevip/config_envvar.go#L93

cc/ @displague

**Comment by displague** [comment]
This was fixed in https://github.com/kube-vip/kube-vip/pull/362.

https://github.com/kube-vip/kube-vip/blob/e9ea905/pkg/kubevip/config_envvar.go#L92-L95
