### ISSUE TITLE
master leader election without kube-proxy fails under >=0.3.9

### ISSUE THREAD

**Issue by schmitch** [kube-vip/kube-vip#359]
**Describe the bug**
kube-vip > 0.3.8 (i.e. 0.3.8 does work) does not work with `kube-proxy`-less mode

we are using kube-vip for k3s+`kube-proxy`-less mode+cilium and it worked great until kube-vip 0.3.8, unfortunatly once we upgraded to 0.3.9 or higher we got strange error messages like:
```
E0207 14:55:22.795574       1 leaderelection.go:322] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp: lookup kubernetes on 1.1.1.1:53: no such host
```
and it did not announce a vip at all (the error is different on 0.4.x:
```
E0207 14:50:51.612419       1 leaderelection.go:330] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp 10.43.0.1:443: i/o timeout
```

btw. this worked up until 0.3.8 and we use it to give cilium's kube-proxy'less mode the vip address. so we actually do not have `kube-proxy` running or a network before `kube-vip` is alive.

**To Reproduce**
1. use kube-ip 0.3.9 or higher instead of 0.3.8
2. kube-vip manifest daemonset \
    --interface $INTERFACE \
    --vip $VIP \
    --controlplane \
    --inCluster \
    --taint \
    --arp \
    --leaderElection | kubectl apply -f -
3. get errory

**Expected behavior**
it should get a vip

**Environment (please complete the following information):**
 - Flatcar linux 3033.2.1 (amd64)
 - v1.23.3+k3s1
 - 0.3.9-0.4.1

**`Kube-vip.yaml`:**
```
 kube-vip manifest daemonset \
    --interface $INTERFACE \
    --vip $VIP \
    --controlplane \
    --inCluster \
    --taint \
    --arp \
    --leaderElection
```

**Additional context**

the cluster is setup really really easily, just dropped k3s with the latest version and the following params:

```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --cluster-init --node-ip 10.10.30.11 --tls-san 10.10.30.10 --tls-san kube-storz.envisia.io --disable servicelb --disable traefik --disable-kube-proxy --flannel-backend=none
```
and of course than bootstraped two other master nodes and ran the rbac/kube-vip-ds

**Comment by ggaurav10** [comment]
I hit the same issue.
Turned out that a new field in the yaml is needed:

https://github.com/kube-vip/kube-vip/pull/285/files#diff-05c0a3fa6e2020efaae62695eb6a1df38af7355bb7ae808a4f6f1ea1aa4acfd5

```
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
```
