### ISSUE TITLE
When v0.4.1, lo is not valid interface

### ISSUE THREAD

**Issue by jieshiyeskey** [kube-vip/kube-vip#360]
env:
k8s: v1.23.3
kube-vip v0.4.1

Note: The service is normal when kube-VIP is v0.4.0.

error:
kube-system   kube-vip-m1     0/1     CrashLoopBackOff   5 (2m16s ago)   5m6s

# kubectl logs kube-vip-m1 -n kube-system
time="2022-02-08T10:53:51Z" level=fatal msg="lo is not valid interface, reason: lo is not up"

yaml:
# cat /etc/kubernetes/manifests/kube-vip.yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "false"
    - name: port
      value: "6443"
    - name: vip_interface
      value: lo
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: bgp_enable
      value: "true"
    - name: bgp_routerid
      value: 192.168.60.61
    - name: bgp_as
      value: "65000"
    - name: bgp_peeraddress
    - name: bgp_peerpass
    - name: bgp_peeras
      value: "65000"
    - name: bgp_peers
      value: 192.168.60.62:65000::false,192.168.60.63:65000::false
    - name: address
      value: 192.168.60.160
    image: ghcr.io/kube-vip/kube-vip:v0.4.1
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}

**Comment by thebsdbox** [comment]
This is fixed in the current release tagged `:main`, I will attempt to create a new release this week.
