### ISSUE TITLE
Not a bug, question about mapping multiple services to a single IP. 

### ISSUE THREAD

**Issue by bayeslearner** [kube-vip/kube-vip#376]
Is it possible to assign a single IP (like gke's global static IP using kubernetes.io/ingress.global-static-ip-name ) to multiple services? If not, any suggestion on how to automate the process of mapping the assigned IP (of a service) to DNS name in ingress (traefik) manifest?

Thanks.

**Comment by bayeslearner** [comment]
I guess this is related to #187

**Comment by thebsdbox** [comment]
At the moment it wouldn't work as the `iptables` rules internal to the Kubernetes cluster would probably implode. Something higher lever would be required, Such as an external load-balancer or DNS round robin.. I *will* get back to the DNS provider at some point.
