### ISSUE TITLE
second kube-vip on cluster

### ISSUE THREAD

**Issue by alexandershelega** [kube-vip/kube-vip#378]
I want to have second VIP for worker nodes, but when create another daemon set it detect first daemon set master and nothing happened, i'm sure it will work when first daemon set will unavaliable, It is possible to have second daemon set deployed on worker nodes with another IP address?

**Comment by thebsdbox** [comment]
If this is for HA that that is unfortunately impossible.. The HA VIP *has* to run on the control plane nodes so that when the traffic hits the VIP it is then forwarded to that local node. Now IPVS could solve this but it hasn't really been tested in that particular way.

**Comment by zrav** [comment]
I think the option of having separate vIPs for the apiserver and the services is a pretty important feature, there are scenarios where it is necessary. I hope this gets implemented.

**Comment by thebsdbox** [comment]
The Control Plane vip and the services vips are completely separate actions, they can't share the same address. You can have two deployments of kube-vip, one doing HA the other doing services.. the control-plane ds needs to live on the control-plane nodes.

**Comment by antimion** [comment]
@thebsdbox i have setup two separate kube-vip, but second one detect first deployment and don't up second ip address configured for services.

**Comment by thebsdbox** [comment]
One should be configured for control plane and the other services. If you mix them then it would end up broken.

**Comment by antimion** [comment]
Maybe you have some instructions how i can properly configure second vip-kube?

**Comment by thebsdbox** [comment]
Only one deployment should enable control plane functionality, the other one should only enable services capability.
