### ISSUE TITLE
[Table Mode] Instead of doing ARP or BGP or assigning IPs to interfaces just export them into a linux kernel table.

### ISSUE THREAD

**Issue by Cellebyte** [kube-vip/kube-vip#379]
**Is your feature request related to a problem? Please describe.**
I want to have a linux like approach to hook into endpoints which are available on the host.

**Describe the solution you'd like**
An additional mode named Table which exports assigned /32 /128 ips into the kernel table if they have a valid endpoint on the node.
This can then be leveraged by a more complex routing system.

**Describe alternatives you've considered**
arp.
bgp

**Additional context**

**Comment by thebsdbox** [comment]
Sure, I think this sort of thing should work with a bad BGP configuration for testing.

**Comment by Cellebyte** [comment]
@thebsdbox for more information of how that can look like -> https://github.com/cybozu-go/coil/blob/main/docs/usage.md#user-manual

**Comment by thebsdbox** [comment]
Just to double check, this is largely just adding an entry to the routing table for an interface? (im a little confused about that I'm implementing 😂, if you're on the Kubernetes slack pop into the #kube-vip channel so we can discuss this if possible)

**Comment by Cellebyte** [comment]
So @thebsdbox  and @Cellebyte  agreed on a new Option which can toggle `TableMode`.
As described it would output the /32 or /128 Routes into a different kernel table then the default one if the `table_id` is altered by the user.
An interface is still required and in this case it should be `lo` or an interface of kind `Dummy`.

All Announcing parts (`BGP` or `ARP`) must be disabled as `Cilium` does, when you put it in non routing mode.
To actively export the routes to an external entity/router you need to first import them into `frr` or `BIRD` and then export it from there. This allows better integration in more complex routing environments.
