### ISSUE TITLE
Can't use WLAN interface as vip_interface

### ISSUE THREAD

**Issue by mposdev21** [kube-vip/kube-vip#390]
**Describe the bug**

I am trying to use the WiFi interface on my laptop as the vip_interface.  I am using this with DHCP to acquire a dynamic address for the VIP. It fails because it can't find the interface. I am using this for my local test setup.

**To Reproduce**
1. kubectl apply -f kube-vip.yml
2. kubectl expose deployment hello-eks-a --port=80 --type=LoadBalancer --name=hello-eks-service --load-balancer-ip=0.0.0.0
3. Check the pod logs and you will see an error "not a valid interface"

**Expected behavior**
Should be able to use the WiFi interface 

**Screenshots**
time="2022-04-15T17:33:03Z" level=info msg="Service [hello-eks-service] has been addded/modified, it has an assigned external addresses [0.0.0.0]"
time="2022-04-15T17:33:03Z" level=error msg="Error finding VIP Interface, for building DHCP Link : Link not found"

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 2104]
 - Kubernetes Version: [e.g. v.1.22]
 - Kube-vip Version: [e.g. 0.3.5]

**`Kube-vip.yaml`:**
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      hostNetwork: true
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: "**wlp164s0**"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: svc_enable
          value: "true"
        - name: vip_startleader
          value: "false"
        - name: vip_addpeerstolb
          value: "true"
        - name: vip_localpeer
          value: bfd96b9fcdc3:172.17.0.2:10000
        - name: vip_loglevel
          value: "5"
        - name: vip_address
        image: plndr/kube-vip:0.3.5
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      serviceAccountName: kube-vip
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
**Additional context**
The only interface that works is "eth0" but DHCP fails later on because this is not a valid interface on my host. It makes me believe that hostNetwork:true is not taking effect i.e it is not able to see host interfaces.

**Comment by thebsdbox** [comment]
Can you try with the latest image release, that version is quite old?

**Comment by mposdev21** [comment]
Here is the output:

time="2022-04-22T19:17:24Z" level=info msg="Starting kube-vip.io [v0.4.4]"
time="2022-04-22T19:17:24Z" level=fatal msg="wlp164s0 is not valid interface, reason: get wlp164s0 failed, error: Link not found"

I think "hostNetwork: true" does not mean you see all the host interfaces; only the host network is reachable. I have created a simple program to just do this:

package main

import (
    "fmt"
    "github.com/vishvananda/netlink"
    )

func main() {
    _, err := netlink.LinkByName("wlp164s0")
	if err != nil {
		fmt.Println("error finding VIP Interface, for building DHCP Link : %v", err)
        return
	}
    fmt.Println("Worked..")
}

If you run this under with "docker -net host", it prints "Worked". If you deploy this under k8s with hostNetwork:true, it prints the error message. Let me know if I am missing anything

**Comment by thebsdbox** [comment]
This is stale at this point.
