### ISSUE TITLE
Kube-vip does not work with newer Equinix Metal annotations

### ISSUE THREAD

**Issue by enkelprifti98** [kube-vip/kube-vip#393]
**Describe the bug**
The Equinix Metal CCM adds updated node annotations from [CCM 3.3.0](https://github.com/equinix/cloud-provider-equinix-metal/releases/tag/v3.3.0) onwards and kube-vip does not work anymore.

**To Reproduce**
1. Provision k8s cluster with Equinix Metal CCM + kubevip in [annotations mode](https://kube-vip.chipzoller.dev/docs/usage/equinix/#using-annotations).

```
kube-vip manifest daemonset \
  --interface $INTERFACE \
  --services \
  --bgp \
  --annotations metal.equinix.com \
  --inCluster | k apply -f -
```

This is potentially caused by the annotation changes made [here](https://github.com/equinix/cloud-provider-equinix-metal/pull/204).

**Comment by displague** [comment]
The newer service annotations are documented in this table <https://github.com/equinix/cloud-provider-equinix-metal/#configuration> and look like the following:

```
      metal.equinix.com/bgp-peers-0-bgp-pass: ""
      metal.equinix.com/bgp-peers-0-node-asn: "65000"
      metal.equinix.com/bgp-peers-0-peer-asn: "65530"
      metal.equinix.com/bgp-peers-0-peer-ip: 10.1.40.130
      metal.equinix.com/bgp-peers-0-src-ip: 10.1.40.131
      metal.equinix.com/network-4-private: 10.1.40.128/25
```

**Comment by enkelprifti98** [comment]
Hey @thebsdbox ! Any update on this issue?

**Comment by thebsdbox** [comment]
This is now merged, support will in `latest` and the upcoming `0.5.11` release.
