### ISSUE TITLE
How to work with different interface names on different machines?

### ISSUE THREAD

**Issue by withinboredom** [kube-vip/kube-vip#399]
**Describe the bug**
Not every machine will have the same ethernet devices:

Example:

- machine class 1: enp9s0
- machine class 2: enp8s0

Different machines may have different networking capabilities (aka, machine class 2 might have a device that supports PPT protocol and is used as the root NTP server).

You must specify a specific network interface when configuring kube-vip.

Changing this to `eth0` can introduce real [security issues](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/) in a multi-link setup.

**To Reproduce**
1. Build non-homogenous servers
2. Try to configure kube-vip
3. Discover it doesn't work

**Expected behavior**
Should be able to specify a device per node.

**Comment by thebsdbox** [comment]
How are you deploying Kube-Vip? As a daemonset or static pods? If static pods, then each deployment can use a different adapter... if you don't specify an adapter then kube-vip will auto-detect the interface based upon the gateway.

**Comment by withinboredom** [comment]
It is a daemonset.

I tried without specifying an adapter, but it is saying that there is no available node, this error to be specific: https://github.com/kube-vip/kube-vip/issues/228#issuecomment-877918369

**Comment by thebsdbox** [comment]
That error is specific the the cloud controller and not the kube-vip pod itself? What is the output of the kube-vip pods, they should tell you which adapter they've detected. The no available node means usually you have no worker nodes in your cluster.

**Comment by withinboredom** [comment]
> The no available node means usually you have no worker nodes in your cluster.

That makes sense. There are no worker nodes.
