### ISSUE TITLE
ip address sharing between multiple services

### ISSUE THREAD

**Issue by PhilippKuntschik** [kube-vip/kube-vip#420]
MetalLB has a nice feature that lets you [share the same ip address between multiple services](https://metallb.universe.tf/usage/#ip-address-sharing). I would like to ask if the kube-vip architecture would allow an implementation for this exact use case? If so, could you provide some pointers so that I may have a shot?

**Comment by ilbarone87** [comment]
@thebsdbox any chance for this to be implemented to work on same port instead of targeting a different port? This is useful in particular for DNS service in order to use both TCP and UDP.
