### ISSUE TITLE
kube-vip.io/manifests/controller.yaml missing?

### ISSUE THREAD

**Issue by brandonhon** [kube-vip/kube-vip#421]
It looks like https://kube-vip.io/manifests/controller.yaml is no longer available. However, https://kube-vip.io/manifests/rbac.yaml is still available. Can you fix or are you moving these manifests to GitHub permanently?

**Comment by thebsdbox** [comment]
Ah apologies, the website move was more complicated than first expected. The controller.yaml should come from the cloud controller repo.

**Comment by thebsdbox** [comment]
Yes, that points to the latest release of the cloud controller :-) I'll try and do a redirect on the main site.

**Comment by brandonhon** [comment]
You da man!
