### ISSUE TITLE
helm chart broken?

### ISSUE THREAD

**Issue by networkop** [kube-vip/kube-vip#425]
**Describe the bug**
Can't add helm repo, getting a 404 error

**To Reproduce**
1. Run `helm repo add kube-vip https://kube-vip.io/helm-charts`
```
$ helm repo add kube-vip https://kube-vip.io/helm-charts
Error: looks like "https://kube-vip.io/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://kube-vip.io/helm-charts/index.yaml : 404 Not Found
```

**Comment by thebsdbox** [comment]
It is indeed broken.. by me (doh) The website move recently will have caused this. 

FIX incoming.

**Comment by voarsh2** [comment]
Thought I'd mention that I get the following error on Rancher RKE1 with helm:


Failed to parse response from https://kube-vip.io/helm-charts/index.yaml

**Comment by thebsdbox** [comment]
Strange I'll investigate.

**Comment by Giancarlo1974** [comment]
it doesn't work for me
Do I need to change repositories?

**Comment by fuog** [comment]
still 404 for me

**Comment by thebsdbox** [comment]
This is really weird, looks like netlify redirect isn't working as expected.. for now -> https://kube-vip.github.io/helm-charts/

**Comment by atropos112** [comment]
the  https://kube-vip.github.io/helm-charts/ address works, i noticed the tag on that chart is for `v0.4.1` does that mean that
a) The chart is fine and works with most up to date (and hence wasn't updated) and all that needs to be changed is the tag or
b) The chart is outdated and will likely not work with `v0.5.5` and newer ?

**Comment by voarsh2** [comment]
..............
Why is the chart still outdated?

**Comment by thebsdbox** [comment]
Unfortunately no one has stepped up to maintain it and I’ve never used helm so don’t really know where to help.

**Comment by thebsdbox** [comment]
I believe the chart has been updated thanks to some new contributors.
