### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by grossgrundbesitzer** [kube-vip/kube-vip#433]
**Describe the bug**
I followed all the steps in the installation guide for Installation of KubeVIP as a Static Pod (ARP) with containerd. Installation with Docker works as expected, but with containerd it doesn't. 

**To Reproduce**
1. export VIP=192.168.178.222
2. export INTERFACE=eth0 
3. KVVERSION=$(curl -sL https://api.github.com/repos/kube-vip/kube-vip/releases | jq -r ".[0].name")
4. alias kube-vip="ctr run --rm --net-host ghcr.io/kube-vip/kube-vip:$KVVERSION vip /kube-vip"
5. kube-vip manifest pod \
    --interface $INTERFACE \
    --address $VIP \
    --controlplane \
    --services \
    --arp \
    --leaderElection | tee /etc/kubernetes/manifests/kube-vip.yaml

The following error occurs: 
ctr: image "ghcr.io/kube-vip/kube-vip:v0.5.0": not found

Running the same steps with but with <alias kube-vip="docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION"> works fine. 

As I am trying to avoid docker, I would try do let it work directly with containerd. 

**Expected behavior**
Installation of kube-vip

**Environment (please complete the following information):**
 - OS/Distro: CentOS Linux release 7.9.2009 (AltArch)
 - Kubernetes Version: 1.24.3
 - Kube-vip Version: 0.5.0

**Additional context**
Running on RPI4 directly connected to Network and to the web.

**Comment by NgHuuAn** [comment]
Same problem with Ubuntu 22.04 LTS

**Comment by linsite** [comment]
Event docker won't pull image automatically, why not pull the image at first?

**Comment by thebsdbox** [comment]
Docs updated, you need to pull the image first with `ctr`

**Comment by CaptKay** [comment]
I am going through this and it is a big headache. The image was pulled, and it's still not working.

**Comment by linsite** [comment]
What is your pull command? Maybe because in a different namespace. k8s demand the image is in k8s.io containerd namespace.
