### ISSUE TITLE
How to deploy on Rancher Desktop?

### ISSUE THREAD

**Issue by vielmetti** [kube-vip/kube-vip#436]
**Is your feature request related to a problem? Please describe.**

I'm trying to deploy kube-vip to a Rancher Desktop installation. The system uses k3s underneath, so I'm pretty certain that once I get it installed it will work. But there's a documentation gap in that https://kube-vip.io/docs/usage/k3s/ isn't specific to the Rancher Desktop environment. 

**Describe the solution you'd like**

I'd like to deploy kube-vip to Rancher Desktop on my local machine (MacBook Air M1) in order that I can have a service type LoadBalancer sufficient to run Acorn.

**Describe alternatives you've considered**

Rancher Desktop has a GUI so I can try to cut-and-paste things into it to make it work, though it's not clear exactly where I would pass in all of the necessary flags like `--disable servicelb` to k3s when it's started.

I could run this on vanilla k3s as an alternative and skip Rancher Desktop, which would reduce the problem to something that's known to work; at the expense of losing the Rancher Desktop GUI.

I could ask the Rancher Desktop team what they think, (and probably will once I get some kind of readout here on how or whether this might work).

**Additional context**

The real goal is a fully working Acorn installation, and since that system is currently v0.1.0 there might be evolution of that system to make this all easier.

**Comment by vielmetti** [comment]
Perhaps related is this issue https://github.com/rancher-sandbox/rancher-desktop/issues/578 which describes an "override.yml" file in which you can set a K3S_EXEC variable for flag setting.

**Comment by thebsdbox** [comment]
Docs are here -> https://kube-vip.io/docs/usage/rancher-desktop/

**Comment by thebsdbox** [comment]
There is still the issue of lima networking, which i've not had the time to grok.

**Comment by thebsdbox** [comment]
Closing this as it is stale
