### ISSUE TITLE
Rancher RKE1: LAN IP Load Balancer for service

### ISSUE THREAD

**Issue by voarsh2** [kube-vip/kube-vip#437]
I can't work out if this project can help me do the following:

Expose a K8 service on the local network with a virtual LAN IP that is not tied to one node (for high availability). 
I want to connect some legacy software to a database and not use nodeport as the way to reach the database from outside K8.

**Comment by thebsdbox** [comment]
Yes, you can create the database as a pod/deployment and expose it using a virtual IP address with kube-vip and a Kubernetes service.
