### ISSUE TITLE
provide default manifests

### ISSUE THREAD

**Issue by omniproc** [kube-vip/kube-vip#438]
The [examples](https://github.com/kube-vip/kube-vip/tree/main/example/deploy) provided are outdated. It would be great to simply get a default manifest e.g. as the [kube-vip-cloud-provider](https://github.com/kube-vip/kube-vip-cloud-provider/tree/main/manifest) repo does that is simply included within the repository. If someone needs a specific version of the manifest the matching Git tag can be used for that - no need for a folder structure of ever growing examples for every version.

Such a default manifest should contain all configuration options with safe/reasonable defaults. It can serve as a example/config lookup of what's possible or be used for building customized deployments using overlays on top of the provided default manifest in cases where a user can not or does not intend to use [Helm](https://github.com/kube-vip/helm-charts) for deployments.

**Comment by omniproc** [comment]
I guess the logic for this is already [here](https://github.com/kube-vip/kube-vip/blob/1ef35923057160d9862d5c71e27e7e3238bedff3/Makefile#L96). It's just not in the CI pipe and not being pushed back to the repo yet.

**Comment by thebsdbox** [comment]
I'll look into having it added into the pipeline.

**Comment by omniproc** [comment]
I just found that this already seems to be done [here](https://github.com/kube-vip/kube-vip/blob/1ef35923057160d9862d5c71e27e7e3238bedff3/Makefile#L96) but the result is pushed to[ /docs/manifests](https://github.com/kube-vip/kube-vip/tree/main/docs/manifests). SO I guess the [examples](https://github.com/kube-vip/kube-vip/tree/main/example/deploy) directory is outdated? If so a `.md` in that folder could point users into the right direction where to find up-to-date manifest files.

**Comment by omniproc** [comment]
> I'll look into having it added into the pipeline.

Yes I just noticed the last updates to the [/docs/manifests](https://github.com/kube-vip/kube-vip/tree/main/docs/manifests) folder are outdated as well.

**Comment by thebsdbox** [comment]
Examples and how to create them exist within the documentation.
