### ISSUE TITLE
Control Plane HA not clear

### ISSUE THREAD

**Issue by aduzsardi** [kube-vip/kube-vip#439]
Hi and thank you for putting in the work so that we can play with k8s locally.
One thing i don't quite understand or it's a bit unclear , regarding control plane ha ... can't you just use a service of type LoadBalancer instead of having all that configuration ? What would be the issue ?
For example on a default microk8s install there's a service like
```└─$ ▶ kubectl describe svc kubernetes 
Name:              kubernetes
Namespace:         default
Labels:            component=apiserver
                   provider=kubernetes
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.152.183.1
IPs:               10.152.183.1
Port:              https  443/TCP
TargetPort:        16443/TCP
Endpoints:         192.168.100.109:16443
Session Affinity:  None
Events:            <none>
```

Say i have 3 nodes (so a HA setup) , could i just set the service to be type LoadBalancer and achieve the same thing as you would with kube-vip control plane ha ?

Thank you!

**Comment by linsite** [comment]
The key point you mssing I guess is that k8s service is done by kube-proxy, and kube-proxy is a DaemonSet. A DaemonSet pod can only be started when kubelet connected to the kube-apiserver. That the dependencies are as below:
 
```
Service -> kube-proxy -> kubelet -> HA
```

So the k8s control-plane HA can't be gained by k8s Service itself, as kubelet depends on that.  Otherwise, that'll be a loop dependency. That's why kube-vip( static pod) is needed.

**Comment by aduzsardi** [comment]
Thanks @linsite , i didn't realize that and i'm keep re-reading your reply and still don't understand how kube-vip( static pod) control-plane HA is any better than having the service exposed as type LoadBalancer . 

Possible that my confusing is coming from the fact that microk8s doesn't have separate worker node vs control-plane node , in which case the kubernetes service will be there either way if i have a working k8s cluster , no dependency loop 
Am i mistaken ?
Sorry if i'm just rumbling nonsense here , i just want to understand better what's going on

**Comment by linsite** [comment]
Yeah, kube-vip is designed for a production k8s cluster, not for microk8s, in which case you have only 1 k8s node(control-plane), HA won't be needed at all, right?

**Comment by aduzsardi** [comment]
Yep that's correct , but as i noted in the first post of the thread/issue you can have multiple nodes (so a HA setup) but you still don't have separate worker nodes vs control-plane nodes 
https://microk8s.io/docs/high-availability

So my question i guess is , would you need kube-vip to provide control-plane HA in this case , or you can just use the default kubernetes service exposed as a LoadBalancer type. :)
Thank you!

**Comment by linsite** [comment]
I think the key point you are confusing is that a LoadBalancer type Service in k8s need a external cloud provider which is implemented by kube-vip.  Here is the document quoted from kubernetes.io

> [LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer): Exposes the Service externally using a cloud provider's load balancer. NodePort and ClusterIP Services, to which the external load balancer routes, are automatically created.

**Comment by thebsdbox** [comment]
This is stale at this point.
