### ISSUE TITLE
kube-vip to install VIP between clusters located in two different geographical locations

### ISSUE THREAD

**Issue by reddybhavaniprasad** [kube-vip/kube-vip#443]
**Is your feature request related to a problem? Please describe.**
I have two sets of kubernetes clusters locates in two different regions with kube-vip installed on each cluster. I want use one of the clusters as an Active cluster and the other as a Standby cluster by using keepalived but that is not working as expected.

**Describe the solution you'd like**
I want kube-vip to assign a VIP to the control plane nodes of the Active cluster and when they fail the same VIP needs to be assigned to the control plane nodes of the Standby cluster. This way I want to achieve HA using kube-vip.

**Describe alternatives you've considered**
I have tried keepalived to drive the traffic between the VIPs of both the clusters but it is not successful.

**Additional context**
It would be very helpful if the VIP is assigned to one of the clusters based on some custom parameters like the latency etc

**Comment by thebsdbox** [comment]
Old issue, closing. (please re-open if this is still a problem)
