### ISSUE TITLE
The --serviceElection flag in the documentation is wrong should be --servicesElection

### ISSUE THREAD

**Issue by thpang** [kube-vip/kube-vip#451]
**Describe the bug**
In the documentations section the `--serviceElection` flag is incorrect. The flag should be listed as `--servicesElection`

Link to the [Flags section](https://kube-vip.io/docs/installation/flags/#flags) of the docs.

**To Reproduce**
1. Add `--serviceElection true` to your `ctr run . . .` command to generate your kube-vip.yaml.

**Expected behavior**
1. Add `--servicesElection true` to your `ctr run . . .` command to generate your kube-vip.yaml

**Comment by thebsdbox** [comment]
Fixed.

**Comment by si458** [comment]
this hasnt been fixed on the main website, ive submitted a PR for you
https://github.com/kube-vip/website/pull/22
