### ISSUE TITLE
plndr-cp-lock": context deadline exceeded

### ISSUE THREAD

**Issue by huisebug** [kube-vip/kube-vip#453]
E0921 02:44:15.096489       1 leaderelection.go:330] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": context deadline exceeded
I0921 02:44:15.096571       1 leaderelection.go:283] failed to renew lease kube-system/plndr-cp-lock: timed out waiting for the condition
E0921 02:44:15.096653       1 leaderelection.go:306] Failed to release lock: resource name may not be empty

Why does this happen？？？

**Comment by DennisYoung96** [comment]
save with me.
i tried version 0.4.2 and 0.5.0, both end up restarting periodically

**Comment by jdbarnes-isi** [comment]
same issue when initializing a 2nd kubelet using 0.5.5
```
E1109 02:11:20.026321       1 leaderelection.go:330] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": context deadline exceeded
I1109 02:11:20.035993       1 leaderelection.go:283] failed to renew lease kube-system/plndr-cp-lock: timed out waiting for the condition
E1109 02:11:20.038566       1 leaderelection.go:306] Failed to release lock: resource name may not be empty
time="2022-11-09T02:11:20Z" level=info msg="This node is becoming a follower within the cluster"
time="2022-11-09T02:11:20Z" level=fatal msg="lost leadership, restarting kube-vip"
```
however, the 2nd node never gets the lock or leadership.

**Comment by jdbarnes-isi** [comment]
I want to note that I am using static containers with manifest. Once this happens, there is no recovering. no amount of restarting the kubelet seems to make any difference.

**Comment by jehutywong** [comment]
I got the same issue when using version 0.5.7.

**Comment by jehutywong** [comment]
looks like tuning these settings can help, but can't find any explanation in docs.

`        - name: vip_leaseduration
          value: "30"
        - name: vip_renewdeadline
          value: "20"
        - name: vip_retryperiod
          value: "4"
`

**Comment by jehutywong** [comment]
My k8s cluster is setup in 5 enterprise grade servers with NVMe disks. The overall servers load is low with 0 IOwait (0.x si though from time to time.)
I was also suspecting the etcd performance, but the etcdetc check perf is looking good. 

PASS: Throughput is 151 writes/s
PASS: Slowest request took 0.009880s
PASS: Stddev is 0.000335s
PASS

**Comment by devopslyf** [comment]
The same problem was encountered when using version 0.4.1.

**Comment by l453595892** [comment]
I got the same issue when using version *0.5.7*. i find etcd have some problem but i cant solve it, so if it can slove in kube-vip ?

**Comment by i5Js** [comment]
> looks like tuning these settings can help, but can't find any explanation in docs.
> 
> ```
>     - name: vip_leaseduration
>       value: "30"
>     - name: vip_renewdeadline
>       value: "20"
>     - name: vip_retryperiod
>       value: "4"
> ```

Same using 0.6.0 Trying with those values.

**Comment by berlineric** [comment]
same here, 
kube-vip: 0.6.2
kubernetes: 1.26.8
os: u20

getting:
`time="2023-10-12T02:07:56Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
E1012 02:40:17.805087       1 leaderelection.go:327] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": context deadline exceeded
I1012 02:40:17.805134       1 leaderelection.go:280] failed to renew lease kube-system/plndr-cp-lock: timed out waiting for the condition
time="2023-10-12T02:40:25Z" level=info msg="This node is becoming a follower within the cluster"
time="2023-10-12T02:40:25Z" level=fatal msg="lost leadership, restarting kube-vip"`

**Comment by lubronzhan** [comment]
> looks like tuning these settings can help, but can't find any explanation in docs.
> 
> ```
>     - name: vip_leaseduration
>       value: "30"
>     - name: vip_renewdeadline
>       value: "20"
>     - name: vip_retryperiod
>       value: "4"
> ```

We also used these values, haven't run into issue yet

**Comment by HashMind** [comment]
> > looks like tuning these settings can help, but can't find any explanation in docs.
> > ```
> >     - name: vip_leaseduration
> >       value: "30"
> >     - name: vip_renewdeadline
> >       value: "20"
> >     - name: vip_retryperiod
> >       value: "4"
> > ```
> 
> We also used these values, haven't run into issue yet

Here you are~

https://github.com/kube-vip/kube-vip/issues/453#issuecomment-1791524793

**Comment by tuxillo** [comment]
Sounds like the workaround (increasing lease duration, etc) is just covering an underlying issue. I'm experiencing this and I'm a bit lost. Has anyone found any more information about it? Is etcd eventually the culprit?

**Comment by thebsdbox** [comment]
Yes, it's more than likely that `etcd` is having issues, thus causing both the API server and leaderElection issues.

**Comment by tuxillo** [comment]
This was exactly my case, let me explain just in case any bit of information might be useful for anyone.

My DEV cluster (which was deployed via kubespray) is running in VMs and they are connected across a Hetzner vswitch, which requires a MTU of 1400. Unfortunatley, I overlooked this detail and had set it to 1500 in all of the control plane VMs so one of the nodes was having major networking issues. After some tests with iperf3 the problem became pretty clear, so I adjusted the MTU accordingly and all the cluster unstability was gone once etcd was stable enough.

**Comment by thebsdbox** [comment]
Cool, thanks for clarifying the underlying network problems 👍

**Comment by AntonioCayulao** [comment]
> looks like tuning these settings can help, but can't find any explanation in docs.
> 
> ```
>     - name: vip_leaseduration
>       value: "30"
>     - name: vip_renewdeadline
>       value: "20"
>     - name: vip_retryperiod
>       value: "4"
> ```

Is it possible to add those values on the cluster creation config?
I'm using RKE2 and I'd like to add those parameters too but I can't find how to do it on the [doc](https://docs.rke2.io/reference/server_config#components)
