### ISSUE TITLE
Kubevip needs new annotation for service.spec.LoadbalancerIP, since it be deprecated in 1.24

### ISSUE THREAD

**Issue by lubronzhan** [kube-vip/kube-vip#457]
**Is your feature request related to a problem? Please describe.**
LoadbalancerIP field in service will be deprecated in 1.24
It's encouraged to use implemenation specific annotation in the future
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation
>Deprecated Service.Spec.LoadBalancerIP. This field was under-specified and its meaning varies across implementations. As of Kubernetes v1.24, users are encouraged to use implementation-specific annotations when available. This field may be removed in a future API version. (https://github.com/kubernetes/kubernetes/pull/107235, [@uablrek](https://github.com/uablrek))

kube-vip also need to take care of it.
https://github.com/kube-vip/kube-vip-cloud-provider/blob/a9f28b60be5e82b5ce0c26d631be9c217dd874fa/pkg/provider/loadBalancer.go#L148
https://github.com/kube-vip/kube-vip/blob/3979c1fcce1e01b140f9b87762ab1c41944e5b38/pkg/service/watcher.go#L50

**Describe the solution you'd like**
Should come up with a new annotation, or annotations for dual stack

Annotations like `kube-vip.io/loadbalancer-ipv4-IP` Like `kube-vip.io/loadbalancer-ipv6-IP`

**Describe alternatives you've considered**

**Additional context**

**Comment by thebsdbox** [comment]
This is implemented.
