### ISSUE TITLE
Question: multiple pods on different node - using the same egress IP?

### ISSUE THREAD

**Issue by Martin-Weiss** [kube-vip/kube-vip#463]
**Describe the bug**
Is it possible to configure egress in a way that a deployment having multiple PODs on different nodes using the same egress VIP for outgoing traffic?

**To Reproduce**

Cluster with 10 nodes where three have a secondary NIC for egress traffic.
Configure kube-vip with a single VIP to be running on the three egress nodes.
Deploy a deployment with 10 pods - one on each node.
Configure kube-vip for this deployment to do egress over a single VIP.

**Expected behavior**
If a POD is hosted on node1 and egress VIP is on node 4 (secondary 5,6) - the egress traffic POD on node1 should go out via node 4 with the VIP specified in kube-vip.

**Environment (please complete the following information):**
 - OS/Distro: CentOS 7.9
 - Kubernetes Version: 1.22
 - Kube-vip Version: 0.5.5

**`Kube-vip.yaml`:**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "4"
    meta.helm.sh/release-name: kube-vip
    meta.helm.sh/release-namespace: kube-vip
  creationTimestamp: "2022-10-12T14:28:41Z"
  generation: 4
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kube-vip
  namespace: kube-vip
  resourceVersion: "29852231"
  uid: ab939ff7-7cf5-4742-9d70-d939d84b6b34
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-vip
      app.kubernetes.io/name: kube-vip
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-vip
        app.kubernetes.io/name: kube-vip
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: is_edge
                operator: In
                values:
                - "true"
      containers:
      - args:
        - manager
        env:
        - name: vip_address
          value: 10.141.48.13
        - name: cp_enable
          value: "true"
        - name: lb_enable
          value: "false"
        - name: lb_port
          value: "6443"
        - name: svc_election
          value: "true"
        - name: svc_enable
          value: "true"
        - name: vip_arp
          value: "true"
        - name: vip_cidr
          value: "32"
        - name: vip_interface
          value: eth1
        - name: vip_leaderelection
          value: "false"
        image: ghcr.io/kube-vip/kube-vip-iptables:v0.5.5
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-vip
      serviceAccountName: kube-vip
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

```

**Comment by thebsdbox** [comment]
So technically it might be possible in the future however that would probably require routing traffic from a pod to an egress gateway, meaning it doesn't matter where the pod is currently running traffic is always sent to "somewhere", where it is then modified and sent on to it's final destination.

Today the re-write is done in-kernel and therefore everything has to happen on the node where a chosen pod is running. So that's why service election is required and external policy local.

**Comment by Martin-Weiss** [comment]
> So technically it might be possible in the future however that would probably require routing traffic from a pod to an egress gateway, meaning it doesn't matter where the pod is currently running traffic is always sent to "somewhere", where it is then modified and sent on to it's final destination.
> 

Thanks for the fast reply! Understood!

So today having a stateful-set with three replicas on different nodes can not have / share the same egress IP.

And - with a single replica - we need to schedule the POD always on the Node that currently has the right VIP or the other way round - schedule the VIP to the node where the POD is hosted.

For the future it would be great if we could do this trick with the same load balancer that is included in kube-vip, already - just in the "reverse" way.. redirect POD egress -> kube-vip load balanacer -> outgoing..

> Today the re-write is done in-kernel and therefore everything has to happen on the node where a chosen pod is running. So that's why service election is required and external policy local.

I am not deep enough in the solution.. what exactly is the "service election" doing - switching the VIP from one node to an other?

Oh - and for others - could we get these currently existing limitations documented in the egress docs for kube-vip?
(multiple replicas on different nodes / with multiple nodes)

**Comment by todaygood** [comment]
@Martin-Weiss , I recommand you to use kube-ovn cni ,  it can use nat-gateway to solve your problem, meanwhile the nat-gateway   support ha by ecmp routes.

**Comment by thebsdbox** [comment]
This is an old conversation, please feel free to re-open or create a new issue if needed.
