### ISSUE TITLE
how to change control plane floating IP

### ISSUE THREAD

**Issue by Mahesh-Gunda-Maersk** [kube-vip/kube-vip#471]
**Describe the bug**
we have a floating IP of a 3 node cluster, we installed Kubernetes (kubeadm) 
created/etc/kubernetes/manifests/kube-vip.yaml with vip_address value as floating-ip
kubeadm init --control-plane-endpoint=Floating-IP ......... 
kubeadm join <nodes> 
kube-vip.yaml manifest same in all nodes. 
Cluster working fine, kubectl cluster-info --> shows floating IP. 

Now we are in a situation to change Floating-IP to some other value.  
How do we achieve this?  could you please guide with Steps? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804]
 - Kubernetes Version: [e.g. v.1.18]
 - Kube-vip Version: [e.g. 0.2.3]

**`Kube-vip.yaml`:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

**Additional context**

**Comment by omniproc** [comment]
1. Edit /etc/kubernetes/manifests/kube-vip.yaml to use the new IP
2. stop kubelet
3. kill kubevip pods
4. start kubelet

kubevip pod should be re-created which should result in kube-vip editing the relevant linux config files setting the new IP.

**Comment by thebsdbox** [comment]
This is stale, so closing for now.
