### ISSUE TITLE
Allow BGP password to be passed as a kubernetes secret

### ISSUE THREAD

**Issue by khatrig** [kube-vip/kube-vip#486]
Today kube-vip takes BGP password as a clear text input in the pod/ds manifest. This is not recommended in production scenarios.

This is an enhancement request to allow taking BGP password as a Kubernetes secret.

**Comment by joejulian** [comment]
When you install with the helm chart, you can use `envFrom` to use a secret for any of the environment variables.

https://github.com/kube-vip/helm-charts/blob/024029685615ddedac85acd4bb503bca28841361/charts/kube-vip/values.yaml#L32

**Comment by Cellebyte** [comment]
This can be fixed using kubernetes native functionality.
