### ISSUE TITLE
LoadBalancer Service takes > 1 minute to respond in libvirt NAT-networked K8S cluster when called from host

### ISSUE THREAD

**Issue by jrcichra** [kube-vip/kube-vip#488]
**Describe the bug**
I have Kubernetes v1.25.4 running inside libvirt, deployed through `kubeadm`.  I have kube-vip configured for both load balancing the API and `Service` `type: LoadBalancer` through ARP. The K8S API works great from my host machine and I have no issue there; however, when I deploy nginx and a `LoadBalancer` service, it takes upwards of 60 seconds for `curl` to come back. I can ping the IP and `arping` comes back with the expected VM mac address. If I `curl` the VIP address from the system it's locally bound to, it still takes about 2 seconds to come back.

**To Reproduce**
This is the playbook I'm building, which includes all the steps I'm taking to get in this state: https://github.com/jrcichra/k8s-lab
Manual version of steps:
1. Make a NAT libvirt network with DHCP enabled on a portion of the selected subnet.
2. Bring up VMs on that network (3 control-planes, 3 workers preferably), copy over [this](https://github.com/jrcichra/k8s-lab/blob/f9d2c0a14c2c653570006ebfe7b6c589c03d00d1/roles/kubeadm/files/kube-vip.yaml) static pod definition to the control-plane nodes, then initialize the cluster
3. Install flannel with all the defaults
4. [Apply](https://github.com/jrcichra/k8s-lab/blob/main/roles/kubeadm/tasks/main.yml#L100-L106) the kube-vip-cloud-controller and give it a pool of non-DHCP addresses in that same subnet to use. 
5. Deploy an [nginx](https://github.com/jrcichra/k8s-lab/blob/f9d2c0a14c2c653570006ebfe7b6c589c03d00d1/examples/nginx.yaml) `Deployment` and `Service`
6. Get the LB IP from Kubernetes (in my case, `192.168.123.10`) and curl it on port 8080.
```
➜  k8s-lab git:(main) ✗ time curl 192.168.123.10:8080
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
curl 192.168.123.10:8080  0.00s user 0.00s system 0% cpu 1:04.85 total
```
Real time for the curl to come back is about 1m5s.

If I try on a different port (80) which has no service bound on that port, it returns an error instantly:
```
➜  k8s-lab git:(main) ✗ time curl 192.168.123.10
curl: (7) Failed to connect to 192.168.123.10 port 80 after 0 ms: Couldn't connect to server
curl 192.168.123.10  0.00s user 0.00s system 92% cpu 0.005 total
```

**Expected behavior**
Data would be returned within a second on a local VM based K8S cluster when curling from the host , and < 2 seconds when curling from the VM which owns the VIP.

**Screenshots**
Here's a packet capture from the host on the `virbr` network. This is from when I was testing on port 80. The SYN is sent and retransmitted until a minute later we get a SYN ACK from the VIP:
![image](https://user-images.githubusercontent.com/1342149/204119969-ed891414-8dcb-497a-8cbe-1e89a5b8d6a8.png)

**Environment (please complete the following information):**
 - OS/Distro: [e.g. Ubuntu 1804] `debian-11-generic-amd64-20221108-1193.qcow2` guests w/ Arch Linux host
 - Kubernetes Version: [e.g. v.1.18]  v1.25.4
 - Kube-vip Version: [e.g. 0.2.3] 0.5.6

**`Kube-vip.yaml`:**
I have it here: https://github.com/jrcichra/k8s-lab/blob/f9d2c0a14c2c653570006ebfe7b6c589c03d00d1/roles/kubeadm/files/kube-vip.yaml

**Additional context**
I'm continuing to debug, but wanted to raise an issue with my findings. This is a great project and I'd love to have it support `LoadBalancer` inside a libvirt network 😃

**Comment by thebsdbox** [comment]
This looks like it is something to do with libvirt or the linux bridge ignoring the ARP updates. (this is tunable).. but gratouitous ARP should imediately inform the network of network changes)

**Comment by thebsdbox** [comment]
Closing this as it appears to be stale.
