### ISSUE TITLE
Add a command-line option for overriding the path /etc/kubernetes/admin.conf

### ISSUE THREAD

**Issue by eriksjolund** [kube-vip/kube-vip#492]
**Is your feature request related to a problem? Please describe.**

Run the command
```
[root@localhost ~]# docker run \
                             --network host \
                             --rm ghcr.io/kube-vip/kube-vip:v0.5.7  \
                                manifest pod \
                                    --interface enp0s2 \
                                    --address 19.19.19.19 \
                                    --controlplane  \
                                    --services \
                                    --arp  \
                                    --leaderElection | grep path:
      path: /etc/kubernetes/admin.conf
```
In the output there is the path _/etc/kubernetes/admin.conf_. The path does not work for __rke2__ and __k3s__.
(I haven't tested __k3s__ yet but I believe it should fail there).

__rke2__ uses the path _/etc/rancher/rke2/rke2.yaml_ instead of _/etc/kubernetes/admin.conf_.

__k3s__ uses the path _/etc/rancher/k3s/k3s.yaml_ instead of _/etc/kubernetes/admin.conf_.

**Describe the solution you'd like**
I would like a new command-line option.
When running the  `manifest pod` command described above,  I would like to pass an option to override the path  _/etc/kubernetes/admin.conf_

 If the option is not given, the path _/etc/kubernetes/admin.conf_ should be used.

**Describe alternatives you've considered**

I've considered these two alternatives

* Manually editing the output from  the `manifest pod` command described above,
*  Installing the program __yq__ and then pipe the output  from  the `manifest pod` command described above into
    ```
    yq '.spec.volumes[0].hostPath.path = "/etc/rancher/rke2/rke2.yaml"' 
    ```

Reference: https://gist.github.com/flrichar/f2a802db7c9b86e230e0ddd679d4d21b

**Additional context**

**Comment by thebsdbox** [comment]
This is implemented.
