### ISSUE TITLE
[Question] Multiple separate Kube-VIP daemonsets in a single cluster

### ISSUE THREAD

**Issue by brandtkeller** [kube-vip/kube-vip#495]
Would there be any potential conflicts with running multiple Kube-VIP daemonsets in the same cluster that are using the same interface but different ports?

Thinking through support for RKE2 and the separation of the API-server (6443) from the supervisor (9345)

Would love to hear thoughts around known issues or conflcits. I will be testing this logic in the near future.

**Comment by thebsdbox** [comment]
There is nothing wrong with multiple daemonsets in a cluster, you can run them in different namespaces to provide some level of multi tenancy. Be aware though, if you're using prometheus then each daemonset will require a different port as they use hostNetwork.
