### ISSUE TITLE
Control  plane balancing broken with dual stack

### ISSUE THREAD

**Issue by xhejtman** [kube-vip/kube-vip#497]
**Describe the bug**
If nodes are running in dual stack configuration, i.e., having both ipv4 and ipv6 addresses, `lb_enable` cannot be used as it balances ipv4 to both ipv4 and ipv6 addresses in wrong way:
```
ipvsadm -L -n
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.16.62.54:6443 rr
  -> 10.16.62.30:6443             Local   1      0          0         
  -> 32.1.7.24:6443               Local   1      0          0  
```

that ip `32.1.7.24` is actually begining of ipv6 address `2001:718:`. The node has local `10.16.62.30` ipv4 address and also public ipv6 prefix `2001:718:`.

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: 1.24.7
 - Kube-vip Version: 0.5.7

**Comment by thebsdbox** [comment]
This has been implemented.
