### ISSUE TITLE
Switch to .Status.LoadBalancer.Ingress

### ISSUE THREAD

**Issue by chdxD1** [kube-vip/kube-vip#501]
**Is your feature request related to a problem? Please describe.**
Kubernetes has deprecated and will remove the .Spec.LoadBalancerIP field at some point. It should be replaced by annotations to steer any controller which needs to assign IP addresses (like the metallb controller or kube-vip controller are doing). 
However some kube-vip code needs to change to not ignore services without the .Spec.LoadBalancerIP field and instead use the list at .Status.LoadBalancer.Ingress to get the IP addresses to announce.

**Describe the solution you'd like**
Use .Status.LoadBalancer.Ingress to find IPs to announce.

**Describe alternatives you've considered**
None / Deprecation from Kubernetes

**Additional context**
https://github.com/metallb/metallb/issues/1182
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4609

**Comment by thebsdbox** [comment]
The status shouldn't be populated by the ccm (providing the IP address).. so annotations are the way forward, although I've read the issue a few times, I don't think this depreciation is happening any time soon 😀

**Comment by chdxD1** [comment]
I think it is actually the way forward from Kubernetes that the status field shall be populated by the ccm (controlled by annotations). Mainly for two reasons: Multiple LoadBalancer IPs and DualStack support (loadbalancerIP does only support a single IP of course). 
Also I've noticed that when using the MetalLB controller in conjunction with kube-vip as a speaker, when controlling MetalLB with annotations, the IP addresses only gets set in the status instead of the spec.

**Comment by chdxD1** [comment]
In my opinion, interpreting the comment in the API docs, the ccm should look for LoadBalancerIP or annotation (or both) and then set the status field which should then be used by something like kube-vip or the metallb speaker.

**Comment by thebsdbox** [comment]
Hmm.. but to me that seems weird 😂 ... Setting the status means that the loadBalancer is `Ready`. The CCM (in my mind) configure the service design (i.e. spec), then the technology that is providing the networking part should set the status once the networking is done.

**Comment by aojea** [comment]
Just FYI, Deprecated doesn't mean it is going to be dropped https://github.com/kubernetes/kubernetes/pull/107235#issuecomment-1320020675

**Comment by b0bd** [comment]
just discovered this by trying to use cilium LB IPAM.   It sets .Status.LoadBalancer.Ingress, but it doesn't have an ability to announce via ARP/NDP.   It would be really nice for kube-vip to be able to do this.

**Comment by lubronzhan** [comment]
This can be closed since `kube-vip.io/loadbalancerIPs` annotation was implemented in https://github.com/kube-vip/kube-vip/pull/528

**Comment by chdxD1** [comment]
closing because it was implemented by https://github.com/kube-vip/kube-vip/pull/722 👍
