### ISSUE TITLE
Kubenretes node cannot connect kube-apiserver by vip and 8443 port

### ISSUE THREAD

**Issue by prometheus-tao** [kube-vip/kube-vip#508]
**Describe the bug**
Kuberentes cluster architecture is 3 master (control panel) and 3 worker nodes , When I restart one of the master nodes, it will appear that the working node cannot connect to the kube-apiserver, the node to be unready status, Viewing the kubelet log shows that the connection kube-apiserver timed out, When I reboot the node I am able to restore the connection again

**To Reproduce**
Restart one of the master nodes

**Expected behavior**
When I restart the master node all the worker nodes can connect kube-apiserver

**Screenshots**
kubelet[1279]: E0131 11:13:54.806663    1279 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "node1": Get https://xxx.xx.xxx.4:8443/api/v1/nodes/node1?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

If I switch master node ip (xxx.xx.xxx.1) and 6443 port connect is ok.

**Environment (please complete the following information):**
 - OS/Distro:  CentOS Linux 7 (5.4.210-1.el7.elrepo.x86_64)
 - Kubernetes Version: v1.18.20
 - Kube-vip Version: v0.1.1

**`Kube-vip.yaml`:**
localPeer:
  id: xxx.xx.xxx.1
  address: xxx.xx.xxx.1
  port: 10000
remotePeers:
- id: xxx.xx.xxx.2
  address: xxx.xx.xxx.2
  port: 10000
- id: xxx.xx.xxx.3
  address: xxx.xx.xxx.3
  port: 10000
vip: xxx.xx.xxx.4
gratuitousARP: true
singleNode: false
startAsLeader: false
interface: ensxx
loadBalancers:
- name: API Server Load Balancer
  type: tcp
  port: 8443
  bindToVip: true
  backends:
   - port: 6443
     address: xxx.xx.xxx.2
   - port: 6443
     address: xxx.xx.xxx.1
   - port: 6443
     address: xxx.xx.xxx.3
- name: ingress Load Balancer
  type: tcp
  port: 80
  bindToVip: true
  backends:
   - port: 8080
     address: xxx.xx.xxx.2
   - port: 8080
     address: xxx.xx.xxx.1
   - port: 8080
     address: xxx.xx.xxx.3

**Additional context**

**Comment by thebsdbox** [comment]
Hey thanks, 

This is from a really really old version of kube-vip, all of the internal load-balancing and HA logic has completely changed since then. You should be able to do an inplace upgrade.

**Comment by prometheus-tao** [comment]
> Hey thanks,
> 
> This is from a really really old version of kube-vip, all of the internal load-balancing and HA logic has completely changed since then. You should be able to do an inplace upgrade.

I try it upgrade 0.3.5, when restarted vip on master node occur the same issue.

**Comment by prometheus-tao** [comment]
Hey @thebsdbox thanks, I solved it after update to 0.4.0 release of kube-vip
