### ISSUE TITLE
Security Feature:  Enable kube-vip implementation without mounting the admin.conf file

### ISSUE THREAD

**Issue by CrashLoopBackOff-K8s** [kube-vip/kube-vip#514]
**Is your feature request related to a problem? Please describe.**
The current implementation uses a hostpath volume mounting the admin.conf file.  From a security standpoint, this presents increased risk from the hostpath mount, along with potentially exposing the cluster admin config file.

**Describe the solution you'd like**
My understanding from a brief conversation in slack is that currently the admin.conf is used to communicate with the api-server.  I would suggest using a service account token for this communication and removing the dependency on the admin.conf, unless needed by a specific use case.  

**Describe alternatives you've considered**
I tried removing the volume mount and also pointing to a fake / empty configuration file.  The current implementation requires a valid admin config for the pods to come up healthy.

**Additional context**
I believe there would be many environments that could benefit from the added security that this change could provide.  While it is not essential, it could enable more organization to make use of this project.

**Comment by thebsdbox** [comment]
Due to changes in Kubernetes 1.29/1.30 moving forward, `admin.conf` has its permissions reduced. However we still need the underlying tokens to start various pods and speak with the API server as part of `kubeadm init`.
