### ISSUE TITLE
Add an option to disable prometheus 

### ISSUE THREAD

**Issue by oneumyvakin** [kube-vip/kube-vip#533]
**Is your feature request related to a problem? Please describe.**
There is need to add option to enable/disable prometheus
https://github.com/kube-vip/kube-vip/issues/415

**Describe the solution you'd like**
Setting `prometheus_server` to empty string is OK:
```
        - name: prometheus_server
          value: ""
```

**Describe alternatives you've considered**
- add a new flag `enable_prometheus_server` with default value "true" to keep backward compatibilty.
OR
- add a new flag `enable_prometheus_server` with default value "false" to keep prometheus disabled by default because kube-vip pods are:
-- using host network 
-- have an wide permissions: NET_ADMIN, NET_RAW, SYS_TIME
So running extra services inside such pods and exposing this services it's super strange, expanding security impact surface and have high potential in security vulnerabilities.

**Additional context**
-

**Comment by xiaods** [comment]
PR welcome

**Comment by Cellebyte** [comment]
can be achieved by setting `prometheus_server: “”`
