### ISSUE TITLE
k8s leases name allows custom modification

### ISSUE THREAD

**Issue by wuzhihui1123** [kube-vip/kube-vip#535]
I want to deploy two sets of kube-vip under the kube-system namespace of k8s, but the lease name of the service cannot be customized and modified （It's always called plndr-cp-lock）, which makes it impossible to use different lease locks for different kube-vip services. I hope that the lease name of kube-vip can be modified through environment variables
The following is my cluster deployment diagram：
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4246626/227266462-bc192a79-62f1-4263-8348-e237f0494459.png">

**Comment by wuzhihui1123** [comment]
@thebsdbox  Thanks for your tips, I have deployed kube-vip-02 to the pod-router namespace, and configured the following environment variables:
```
env:
  - name: cp_namespace
    value: "pod-router"
```

**Comment by xiaods** [comment]
@wuzhihui1123  Can you share your full tutorial?

**Comment by thebsdbox** [comment]
Closing this as there is no further input.
