### ISSUE TITLE
Support both peers via Equinix Metal annotations

### ISSUE THREAD

**Issue by cprivitere** [kube-vip/kube-vip#543]
**Is your feature request related to a problem? Please describe.**
Addendum to, #521. Add support for both peers. We mistakenly thought that kube-vip could only handle one peer when fixing up the annotations support.

**Describe the solution you'd like**
Get both equinix-metal bgp peers and add them to the comma separated list.

**Comment by enkelprifti98** [comment]
It would be great to have both BGP peers supported via annotations to ensure network redundancy. Currently load balancer services rely on the first BGP peer which in scenarios such as network maintenance events where the primary peer isn't available the service will not be available unless both BGP peers are supported.
