### ISSUE TITLE
How to configure Multiple instances

### ISSUE THREAD

**Issue by W1zzardTPU** [kube-vip/kube-vip#544]
**Is your feature request related to a problem? Please describe.**
I need to provide IP services for two interfaces, one private, one public (plus the control plane)

**Describe the solution you'd like**
Seems this is isnt possible with the default install, so I tried installing two instances of kube-vip. One handling the control plane + one interface, and a second installation for the second interface (without control plane).

Is there any official guidance for how to avoid conflicts?

In a quick test this doe work, but both instances will pick up IPs from the LoadBalancer resource and assign them to their own interface, so now I have the same IP on both interfaces.

How to avoid?

One solution could be to allow customization of the hardcoded "kube-vip.io/kube-vip-class" string, so only one instance processes the IP requests, i.e. in my setup use something like "kube-vip-class-public" and "kube-vip-class-private".

A slightly more complex alternative could be to implement #504

**Comment by W1zzardTPU** [comment]
#546 addresses this and so far it's working well in testing.

Is there anything else that needs to be taken care of for multiple instances to not conflict with each other? 
I only changed the ports for "prometheus_server" and "port". Same namespace seems ok?

**Comment by drustan** [comment]
I'm not sure to understand how this change addresses the multiple interfaces case, since a Kube VIP instance is bound to an interface with the vip_interface parameter. Am I missing something here ?

See https://github.com/kube-vip/kube-vip/issues/532#issuecomment-1490151083 for details concerning my current setup

**Comment by W1zzardTPU** [comment]
Before this patch I've had issues getting my floating IPs bound to the right interface, because the wrong kube-vip instance got selected

**Comment by W1zzardTPU** [comment]
We've been using this setup in production for several months without issue, so I guess it's safe to assume that multiple instances of kube-vip "just works" and this can be closed.
