### ISSUE TITLE
Remove /docs

### ISSUE THREAD

**Issue by thebsdbox** [kube-vip/kube-vip#549]
**Is your feature request related to a problem? Please describe.**
`/docs` is deprecated and everything should be in the the website repo

**Describe the solution you'd like**
We're going to remove it to simplify the code base

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by linsite** [comment]
This seems quite easy, do we have any volunteers? If not, I could give a shot.

**Comment by MaryAyobami** [comment]
Hello @thebsdbox  I'd love to work on this. Can I proceed?

**Comment by AryanParashar24** [comment]
I would like to work on it 😃

**Comment by AHB102** [comment]
@thebsdbox I have created a PR, can you please look into it ?

**Comment by thebsdbox** [comment]
This is fine, the docs already exist in the `/website` repo so they don't need moving over there.

**Comment by AHB102** [comment]
@thebsdbox Can you close this issue and PRs to?

**Comment by thebsdbox** [comment]
This is completed.
