### ISSUE TITLE
Gateway API

### ISSUE THREAD

**Issue by thebsdbox** [kube-vip/kube-vip#550]
**Is your feature request related to a problem? Please describe.**
Implement a gateway API controller

**Describe the solution you'd like**
I'd like a gateway API controller to manage `gatewayClass, gatways, TCPRoute and UDPRoute`.

**Describe alternatives you've considered**
N/A

**Additional context**
This will ultimately go in a new repository under the kube-vip repo (this is for tracking)

**Comment by displague** [comment]
Duplicates https://github.com/kube-vip/kube-vip/issues/288
