### ISSUE TITLE
kube-vip daemonset for controlplane with different vip_interface names

### ISSUE THREAD

**Issue by naiming-zededa** [kube-vip/kube-vip#559]
**Describe the bug**

I'm using k3s HA with kube-vip, which is supported as the daemonset to generate pods
on multiple k3s master nodes. One of the master node has 'eth0' as the interface name,
and the other has name of 'enp3s0'. Since the 1st master started with the manifest for
'vip_interface' with the name of 'eth0', the 2nd node kube-vip-ds pod keep crashing
with error: fatal msg="eth0 is not valid interface, reason: get eth0 failed, error: Link not found".

Since there is no way to guarantee all the controlplane nodes will have the same interface names,
I would consider this as a bug if there is no workaround.

**To Reproduce**

Generate the manifest for k3s on 1st server.
- k3s server -tls-san $VIP --cluster-init
- kubectl apply -f https://kube-vip.io/manifests/rbac.yaml
- curl -sL kube-vip.io/k3s | vipAddress=$VIP vipInterface=eth0 sh | tee /var/lib/rancher/k3s/server/manifests/vip.yaml
- kubectl apply -f  /var/lib/rancher/k3s/server/manifests/vip.yaml

On the 2nd k3s server:
- curl -sfL https://get.k3s.io | K3S_TOKEN=<secret> sh -s - server --server https://$VIP:6443 --tls-san $VIP

**Expected behavior**
I'm not sure how this suppose to work, but since the 2nd master has a different name of interface, we have no way of modifying it.

**Screenshots**
On 2nd k3s master, log the error:
time="2023-05-05T05:14:58Z" level=info msg="Starting kube-vip.io [v0.5.10]"
time="2023-05-05T05:14:58Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2023-05-05T05:14:58Z" level=info msg="prometheus HTTP server started"
time="2023-05-05T05:14:58Z" level=fatal msg="eth0 is not valid interface, reason: get eth0 failed, error: Link not found"

**Environment (please complete the following information):**
 - OS/Distro: [16.04.1 LTS]
 - Kubernetes Version: [v1.26.4+k3s1]
 - Kube-vip Version: [0.5.10]

**`Kube-vip.yaml`:**

apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: eth0
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: svc_enable
          value: "false"
        - name: vip_address
          value: 192.168.x.y
        image: ghcr.io/kube-vip/kube-vip:v0.5.11
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

**Additional context**

Looking for a workaround.

**Comment by thebsdbox** [comment]
Remove the interface from the configuration and it will auto-detect on each node.

**Comment by naiming-zededa** [comment]
Cool @thebsdbox , let me try that. Does the kube-vip uses the 'default route' as a hint without an interface?

**Comment by naiming-zededa** [comment]
ok, i see this, that's fine:

			if initConfig.Interface == "" {
				log.Infof("No interface is specified for VIP in config, auto-detecting default Interface")
				defaultIF, err := vip.GetDefaultGatewayInterface()
