### ISSUE TITLE
Dual stack VIP configuration (env.address)

### ISSUE THREAD

**Issue by drustan** [kube-vip/kube-vip#566]
Hello here!

That's not really an issue but more likely a question. 

I deployed a KubeVIP DaemonSet with these env values :

```
        - name: vip_arp
          value: "true"
        - name: vip_interface
          value: ens161
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "false"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 192.0.2.10
        - name: svc_namespace
          value: "internal"
```

I read that Kube VIP is dual stack compatible so if I want to set an IPv6 VIP address as well on the same interface (ens161), how do I proceed? Do I have to create another DaemonSet with an IPv6 as env.address value or can I specify both IPv4/IPv6 in the same DaemonSet configuration env?

**Comment by lubronzhan** [comment]
Do you mean for control plane HA or for loadbalancer type service.

**Comment by thebsdbox** [comment]
This is an old conversation, please feel free to re-open or create a new issue if needed.
