### ISSUE TITLE
Actions need some version bumps

### ISSUE THREAD

**Issue by cprivitere** [kube-vip/kube-vip#568]
**Is your feature request related to a problem? Please describe.**
Some of the github actions are old and in need of bumps. For example CodeQL version 1 is no longer supported and needs to be bumped to version 2. Others are running on node.js 12 and GitHub will soon disable them.

**Describe the solution you'd like**
Bump the version numbers, test they still work, update any options that need updating.

**Comment by thebsdbox** [comment]
All done and automated with dependabot!
