### ISSUE TITLE
Segmentation fault when removing a service

### ISSUE THREAD

**Issue by EmielBruijntjes** [kube-vip/kube-vip#570]
## The kube-vip setup

We run a single kube-vip pod (kube-vip v0.6.0) with only the following environment variables:
```
- name: svc_enable
  value: "true"
- name: svc_election
  value: "true"
- name: lbClassOnly
  value: "true"
- name: lbClassName
  value: "internal"
- name: vip_arp
  value: "true"
```

The configuration might be wrong (documentation is a bit vague about how to use kube-vip for only hosting ips set in loadbalancers), but it should nevertheless not cause the program to crash.

## The service that we created

Using kubectl, we added and removed the following service

```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: test
spec:
  type: LoadBalancer
  loadBalancerClass: internal
  selector:
    app: whatever
  ports:
  - port: 8997
    targetPort: 8997
    protocol: TCP
```

## The thing that happened
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x172e6b6]

goroutine 1 [running]:
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).servicesWatcher(0xc000355180, {0x1e3edb0?, 0xc000356fc0}, 0xc000700780)
	/src/pkg/manager/watch_services.go:195 +0x956
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).startServicesWatchForLeaderElection(0xc000355180, {0x1e3edb0, 0xc000356fc0})
	/src/pkg/manager/servicesLeader.go:20 +0x74
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).startARP(0xc000355180)
	/src/pkg/manager/manager_arp.go:121 +0x894
github.com/kube-vip/kube-vip/pkg/manager.(*Manager).Start(0xc000355180)
	/src/pkg/manager/manager.go:148 +0x2ab
github.com/kube-vip/kube-vip/cmd.glob..func11(0x2b830e0, {0x1b6445e?, 0x0?, 0x0?})
	/src/cmd/kube-vip.go:339 +0xab5
github.com/spf13/cobra.(*Command).execute(0x2b830e0, {0x2bd0a68, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x2b84220)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kube-vip/kube-vip/cmd.Execute()
	/src/cmd/kube-vip.go:150 +0x25
main.main()
	/src/main.go:17 +0x85
```

**Comment by lubronzhan** [comment]
> documentation is a bit vague about how to use kube-vip for only hosting ips set in loadbalancers
Are you trying to only set the kube-vip for loadbalancer IP? Looks similar to this one https://github.com/kube-vip/kube-vip/issues/530
Right now it's not supported. But I don't see log get posted in the other issue

**Comment by EmielBruijntjes** [comment]
Yes, that's indeed what I am trying to do. I will check that other issue.

But the crash that I am reporting here is an issue on its own (bc software should not crash even when input is wrong). 

To reproduce: if you remove a service of type loadbalancer with the loadbalancerip property not set, kube-vip crashes.

**Comment by thebsdbox** [comment]
Looking at the code now, it’s a simple fix.

-Dan
