### ISSUE TITLE
Multiple services on the same IP conflicts with enableServicesElection

### ISSUE THREAD

**Issue by ouyangde** [kube-vip/kube-vip#577]
**Describe the bug**
When "enableServicesElection" is enabled and multiple services are configured with the same IP, it can result in a situation where the same virtual IP is assigned to multiple hosts.

**To Reproduce**
1. enable Services Election
2. assign SVC1 to 192.168.1.100，SVC2 to 192.168.1.100，SVC3 to 192.168.1.100
3. kubectl describe svc SVC1 SVC2 SVC3 | grep kube-vip.io/vipHost
4. Then it is possible to see different hosts

**Expected behavior**
The same IP should only be assigned to the same host.

**Comment by thebsdbox** [comment]
This is an old conversation, please feel free to re-open or create a new issue if needed.
