### ISSUE TITLE
Ability to include/exclude Kubernetes-nodes in/from kube-vip leader election

### ISSUE THREAD

**Issue by djpbessems** [kube-vip/kube-vip#581]
**Is your feature request related to a problem? Please describe.**
Whenever a new k3s node is added to a cluster running kube-vip; it successfully deploys the kube-vip daemonset and starts a leader election. However, due to the nature of our clusters and workloads (air-gapped environments, running harbor on the cluster itself, upgrades of nodes with a limited set of pre-loaded container images, resulting in different image caches between nodes), we see a chicken-egg situation where harbor becomes unavailable the moment kube-vip changes the new leader, but the supporting images for workloads are not available on the newly added nodes (and cannot pull from other sources because they are air-gapped).

**Describe the solution you'd like**
If I can prevent a newly added node from becoming a leader *until* a certain condition is reached (workloads running in the cluster are upgraded, or image-caches are updated with missing images), I can avoid a cluster from becoming non-functional. 
Probably the best option is relying on labels to tell kube-vip to exclude/include nodes in the election, then I can update the respective label after removing the potential cause for the chicken-egg situation.

**Describe alternatives you've considered**
Killing the kube-vip pod on the new node will trigger a leader-election again, to move kube-vip back to the original node (thereby making harbor available again to pull missing images from)

**Comment by BBQigniter** [comment]
I think you could maybe try my [kube-vip-watcher](https://github.com/BBQigniter/kube-vip-watcher) to handle that

**Comment by Cellebyte** [comment]
Or use kubernetes scheduling if the exclusion should be permanent.
