### ISSUE TITLE
Is it possible to install kube-vip in an air gapped network

### ISSUE THREAD

**Issue by simonjcarr** [kube-vip/kube-vip#586]
I don't have direct access to docker.io, but I do have a nexus repo server on my network.

The nexus repo has a pull through docker proxy to docker.io and I also have a private hosted registry where I have re tagged and pushed the kube-vip image. Both of these repos are on http endpoints (not https)

I can't find a way to configure `ctr` and everything I have read has said that `ctr` ignores the config in `/etc/containerd/confg.toml`

How can I get `ctr` to either use the nexus pull through proxy or the private repository?

**Comment by linsite** [comment]
What is the command you used with 'ctr` ? Your issue doesn't apply to me, I always can pull images from a nexus registry.

**Comment by thebsdbox** [comment]
Surely just specifying the full image path repo/org/image:tag should work in the manifests?

**Comment by brandtkeller** [comment]
This sounds more like a containerd/cluster issue than Kube-VIP. If the docker proxy is https then you should be able to specify that in the manifest as mentioned above provided your cluster can connect to it. Non-encrypted is a different problem as there are more nuances to whether containerd will support that or not. 

For my airgap deployments of Kube-VIP I use [Zarf](https://github.com/defenseunicorns/zarf) to handle the mutation of images to point to internal registries.

**Comment by thebsdbox** [comment]
This is an old issue, please re-open if this needs continuation.
