### ISSUE TITLE
question, does kube-vip support running without kube-proxy ?

### ISSUE THREAD

**Issue by JSN-1** [kube-vip/kube-vip#594]
First of all thanks for a great project 

I am using Cilium as CNI and i tried to get kube-vip-cloud-provider to work without kube-proxy.
[https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/](url)

installed it from [https://kube-vip.io/docs/installation/daemonset/](url) using ARP.

It's working fine with kube-vip for control-plane, but for services using kube-vip-cloud-provider it does not work.

The ip address i get from kube-vip only works on the k8s cluster nodes, not from another server on the same network.

tried both externalTrafficPolicy cluster and local with same result.

My question is does kube-vip support kube-proxy free ?

**Comment by zifeo** [comment]
@thebsdbox Could you be more specific? I have given a shot without looking this issue and so far it looks ok (maybe not on the long-term or stability).
