### ISSUE TITLE
Denial of Service with Multiple LoadBalancer Services On the Same IP

### ISSUE THREAD

**Issue by usiegl00** [kube-vip/kube-vip#600]
When deleting a LoadBalancer Service that [shares an IP](https://kube-vip.io/docs/usage/kubernetes-services/#multiple-services-on-the-same-ip) with other LoadBalancer Services, the IP is released and all services are effectively denied service.
Here is the log that corresponds with this denial of service event:
```
│ time="2023-08-16T02:43:15Z" level=info msg="[LOADBALANCER] Stopping load balancers"                                                               │
│ time="2023-08-16T02:43:15Z" level=info msg="[VIP] Releasing the Virtual IP [xx.xxx.xxx.xx]"                                                        │
│ time="2023-08-16T02:43:15Z" level=info msg="service [servicename/a733-5a62f7c89b49] has been deleted"                         │
│ time="2023-08-16T02:43:15Z" level=warning msg="Re-applying the VIP configuration [xx.xxx.xxx.xx] to the interface [enp2s0f0]"                      │
```
I believe that this is the section of code that would need to be aware of the possibility of a service sharing an IP:
https://github.com/kube-vip/kube-vip/blob/96541380b5a35c75d62deb444a2eabe7a52299b3/pkg/cluster/service.go#L224C27-L224C35

Please let me know if I can provide any additional information to assist in resolving this.

**Comment by thebsdbox** [comment]
Yeah, we actually track this information in a map.. so we probably would need a lookup and a counter to make sure that once ip references reach 0 it can be deleted.
