### ISSUE TITLE
Add a capability to allocate load balancer ip only on hosts which interfaces belongs to subnet specified in the kubevip config for namespace

### ISSUE THREAD

**Issue by Nova-Logic** [kube-vip/kube-vip#605]
Please Add a capability to allocate load balancer ip only on hosts which interfaces belongs to subnet specified in the kubevip config for namespace.

Scenario: 
Secured k8s deployment where control plane  and worker nodes resides in different subnets

Current behaviour:
for example you have this subnets:
1)Control-plane 10.1.42.0/24
2)worker nodes sub: 10.1.43.0/24
Load balancer ip for ingress NGINX from pool configured would be assigned to control-plane nodes and obviously would not work.

Proposed behaviour:
with some config flag ( or may be by-default) kube-vip would follow subnet ranges of host interfaces and would allocate load balancer IP addresses only on nodes that belongs to subnets in config

**Comment by Cellebyte** [comment]
Is the new auto feature doing the trick?

It only works in arp mode, but instead of defining the ip and subnet mask manually it is auto discovered from the node the service ist running on.
Additionally there are new annotations for services. 
Please check out the new release.
