### ISSUE TITLE
[Bug] kube-vip version command returning incorrect version.

### ISSUE THREAD

**Issue by DannyBrito** [kube-vip/kube-vip#615]
**Describe the bug**
Kube-vip version command returning wrong version to be more specific wrong patch number, for images versions ending in `1`, this is seen on image versions: 
- `v0.6.1` (returns `V0.6.0`)
- `v0.5.11`  (returns `V0.5.10`)
- No affected `v0.4.1` (returns `v0.4.1`)

**To Reproduce**
1. `docker run ghcr.io/kube-vip/kube-vip:v0.6.1 version`
```
Unable to find image 'ghcr.io/kube-vip/kube-vip:v0.6.1' locally
v0.6.1: Pulling from kube-vip/kube-vip
Digest: sha256:af2b9b883f90fea0868342498ffc922694ab250b938e3d3271ed223180dcf20b
Status: Downloaded newer image for ghcr.io/kube-vip/kube-vip:v0.6.1
Kube-VIP Release Information
Version:  v0.6.0
Build:    c54994e9b790cdf6670bb45093d10a6e6d5b7a47
```
**Expected behavior**
Version Command should reflect correct patch # for affected images.

EDIT: 
I think this issue is specific to not updated Makefile variable `VERSION` for when `v0.6.1` and `v.0.5.11` tags were cut.
https://github.com/kube-vip/kube-vip/blob/v0.6.1/Makefile#L8C1-L8C18
https://github.com/kube-vip/kube-vip/blob/v0.5.11/Makefile#L8

**Comment by thebsdbox** [comment]
We've corrected for subsequent versions.
