### ISSUE TITLE
BGP not working OR Documentation not working

### ISSUE THREAD

**Issue by Ashkaan** [kube-vip/kube-vip#616]
**Describe the bug**
BGP does not seem to function properly.  It does not send any data to my firewall.

**To Reproduce**
1) Configure kube-vip in BGP mode using [this guide](https://kube-vip.io/docs/installation/daemonset/)
2) Install FRR plugin on PFSense (firewall).
3) Enable FRR, add Router ID, and master password
<img width="1153" alt="image" src="https://github.com/kube-vip/kube-vip/assets/5667978/273d24e3-19ea-4022-86ad-126c746671e9">

4) Enable BGP, add Local AS, and Router ID
<img width="1152" alt="image" src="https://github.com/kube-vip/kube-vip/assets/5667978/774281fc-ebe8-4f59-9e5d-34306a151674">

5) Disable eBGP
<img width="1158" alt="image" src="https://github.com/kube-vip/kube-vip/assets/5667978/942c7418-00ee-4b67-9680-9322dd33fa37">

**Expected behavior**
Watch the status page for prefixes to populate and MsgRcvd MsgSent.
<img width="1155" alt="image" src="https://github.com/kube-vip/kube-vip/assets/5667978/baac10f6-f768-4d4b-ad4d-ddcec95794e7">

**`Kube-vip.yaml`:**
apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    name: kube-vip-ds
    version: v0.6.2
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
        version: v0.6.2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "false"
        - name: port
          value: "6443"
        - name: vip_interface
          value: "eth0"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: bgp_enable
          value: "true"
        - name: bgp_routerid
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: bgp_routerinterface
          value: "eth0"
        - name: bgp_as
          value: "65000"
        - name: bgp_peeraddress
        - name: bgp_peerpass
        - name: bgp_peeras
          value: "65000"
        - name: bgp_peers
          value: 10.1.0.75:65000::false,10.1.0.76:65000::false,10.1.0.77:65000::false
        - name: address
          value: 10.1.0.101
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:latest
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

(I tried to format as a code block, but it just scrunched everything together.  A Google didn't help.)

**Additional context**
K3S (latest) on Ubuntu 22 LTS.

**Comment by Cellebyte** [comment]
probably will be fixed soon with #730 and #695

**Comment by Cellebyte** [comment]
@Ashkaan could you test this with the latest version?

**Comment by Ashkaan** [comment]
After struggling with this for weeks and no answer here, our team moved to a working product.

**Comment by Cellebyte** [comment]
Ok. So case closed. Thanks for feedback :)
