### ISSUE TITLE
vip_leasename Setting for Multiple Instances with Dual Stack IPv4/IPv6

### ISSUE THREAD

**Issue by jjschwarz** [kube-vip/kube-vip#625]
Should the value of vip_leasename be left as plndr-cp-lock for both the IPv4 and IPv6 instances of kube-vip when running dual stack (with one instance running as manager and the other using start)?

**Comment by thebsdbox** [comment]
Moving forward `manager` should be the only path to starting kube-vip. You would theoretically want different lease names between IPv4 and IPv6.

**Comment by jjschwarz** [comment]
OK, so then we should get rid of the "start" and just change rometheusHTTPServer value to "" for the second (IPv6) instance in this case?  

Is there a way to set the vip_leasename  from the command line?  I was not seeing that in the code.

**Comment by thebsdbox** [comment]
`--leaseName` and `--servicesLeaseName` are for specifying leases.

**Comment by jjschwarz** [comment]
OK, and if running two copies I should specify both, correct?

How about start vs manager, just drop start and set the prometheusHTTPServer to blank?

**Comment by jjschwarz** [comment]
I attemped to use the --servicesLeaseName with v0.6.2 but it came back with an error stating that was not an option during the manifest generation.

**Comment by thebsdbox** [comment]
Ah! I see.. it's missing from the `config_generator.go` file!

`go run main.go manifest pod --servicesLeaseName bob --leaseName test` - generates a manifest, but the manifest doesn't have the environment variables defined!

**Comment by jjschwarz** [comment]
OK, so any chance that will be fixed up in an upcoming release?

**Comment by thebsdbox** [comment]
Yeah, I'm doing it now (in the meantime you can still put the correct environment variables in the manifest)

**Comment by jjschwarz** [comment]
The manifest also seems to always generate with the name as kube-vip.  Obviously with multiple manifests (one for IPv4 and one for IPv6) I have to manually rename it (well I use a script).  Is there an option I am missing to produce the manifest with an alternative name?  I found the option for alternative namespace, but right now I was keeping them in the same namespace for simplified management.

**Comment by jjschwarz** [comment]
I manually put them in this time, but I am trying to optimize the process so I can script it out and stand up a new cluster quickly (or in my case stand up the same one again with different underlying OS and hardware stacks).

**Comment by jjschwarz** [comment]
Any idea which version will have the updated flag?

**Comment by thebsdbox** [comment]
Ah, so it's confusing and I'm not 100% sure where the logic came from..
`--leaseName` requires `--leaderElection` to be set and `--servicesLeaseName` requires `--services` to be set.

**Comment by jjschwarz** [comment]
I have both leaderElection and services set, so when the version with the update flag releases I think I should be good.  
Any thoughts on the manifest name itself, because right now that appears to still have to be changed by hand for multiple instances?

**Comment by jjschwarz** [comment]
I believe the v0.6.3 release fixed the servicesLeaseName issue, so that just leaves case 630 to fix the prometheus issue so that we can clear out the manager vs start issue
