### ISSUE TITLE
Dual stack services advertised both advertised by IPv4 kube-vip 

### ISSUE THREAD

**Issue by jjschwarz** [kube-vip/kube-vip#631]
**Describe the bug**
Dual stack kube-vip setup with two instances will have the IPv4 instance advertise both IPv4 and IPv6 service addresses.

**To Reproduce**
1. Create an IPv4 load balancer for both control plane and service load balancing
2. Create an IPv6 load balancer for both control plane and service load balancing with distinct lease names
3. Deploy a service with an IPv4 load balancer address and another service with an IPv6 load balancer address for a pod

**Expected behavior**
I expect the IPv4 load balancer to handle the IPv4 address and the IPv6 load balancer to handle the IPv6 address.

**Log from IPv4 instance**
time="2023-10-17T15:56:26Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[true]"
time="2023-10-17T15:56:26Z" level=info msg="prometheus HTTP server started"
time="2023-10-17T15:56:26Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2023-10-17T15:56:26Z" level=info msg="beginning services leadership, namespace [kube-system], lock name [plndr-svcs-lock], id [k8s-3.breepriv.lothlorien.net]"
I1017 15:56:26.649538       1 leaderelection.go:245] attempting to acquire leader lease kube-system/plndr-svcs-lock...
time="2023-10-17T15:56:26Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [k8s-3.breepriv.lothlorien.net]"
I1017 15:56:26.652269       1 leaderelection.go:245] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2023-10-17T15:56:26Z" level=info msg="new leader elected: k8s-1.breepriv.lothlorien.net"
I1017 15:56:26.752016       1 leaderelection.go:255] successfully acquired lease kube-system/plndr-cp-lock
time="2023-10-17T15:56:26Z" level=info msg="Node [k8s-3.breepriv.lothlorien.net] is assuming leadership of the cluster"
time="2023-10-17T15:56:26Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.254.80]"
I1017 15:56:33.093031       1 leaderelection.go:255] successfully acquired lease kube-system/plndr-svcs-lock
time="2023-10-17T15:56:33Z" level=info msg="starting services watcher for all namespaces"
time="2023-10-17T16:29:49Z" level=info msg="[service] adding VIP [192.168.254.100] for [default/web-breelb]"
time="2023-10-17T16:29:49Z" level=info msg="[service] synchronised in 39ms"
time="2023-10-17T16:34:01Z" level=info msg="[service] adding VIP [2620:128:2000:254::100] for [default/web-breelb-v6]"
time="2023-10-17T16:34:01Z" level=info msg="Broadcasting NDP update for 2620:128:2000:254::100 (00:50:56:95:78:a0) via ens192"
time="2023-10-17T16:34:01Z" level=info msg="ndp: &{false false true 2620:128:2000:254::100 [0xc00058fcc0]}"
time="2023-10-17T16:34:01Z" level=info msg="[service] synchronised in 43ms"
time="2023-10-17T16:34:04Z" level=info msg="Broadcasting NDP update for 2620:128:2000:254::100 (00:50:56:95:78:a0) via ens192"
time="2023-10-17T16:34:04Z" level=info msg="ndp: &{false false true 2620:128:2000:254::100 [0xc00058ef40]}"

**Environment (please complete the following information):**
 - OS/Distro: AlmaLinux 8.8
 - Kubernetes Version: v1.26.7
 - Kube-vip Version: v0.63

**`Kube-vip.yaml`:**
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens192
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.254.80
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.6.3
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip6-ds
  namespace: kube-system
spec:
  containers:
  - args:
    - start
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens192
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock6
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock6
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 2620:128:2000:254::80
    image: ghcr.io/kube-vip/kube-vip:v0.6.3
    imagePullPolicy: Always
    name: kube-vip6-ds
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}

**Comment by lubronzhan** [comment]
You can specify the loadbalancerClass in kube-vip for ipv6, then add loadbalancerClass field for ipv6 service, then only the kube-vip for ipv6 will advertise service with that loadbalancerClass

**Comment by jjschwarz** [comment]
OK, so two questions on your answer:

**Comment by jjschwarz** [comment]
I am thinking it might be lbClassName based on a quick search of the code, but I am not seeing that in the code to generate a manifest.

**Comment by thebsdbox** [comment]
`lbClassName` is defined on a service itself.. Kube-vip will then watch for it and if the class name matches then it will advertise it.

**Comment by jjschwarz** [comment]
Right, but this is dual stack, so I have two copies of kube-vip running and they are both listening for the same class name.  I am trying to figure out how to force each one to pick a unique name so I can steer IPv6 services to the IPv6 kube-vip instead of them going to the IPv4 kube-vip.

**Comment by thebsdbox** [comment]
Ah ok.. I'll need to fix the manifest generation then I guess! (good catch).. I'm not sure there is a way we can automate the process of adding flags and ensuring the environment variables are created too. Guess I'll need to improve the due diligence in PRs. I'll get it fixed.

**Comment by QuinnBast** [comment]
Seems like this feature would also work for this and would prevent people from needing to deploy kube-vip twice if they have two network interfaces:

https://github.com/kube-vip/kube-vip/issues/504

**Comment by thebsdbox** [comment]
PR has been merged for complete support (with ARP), new release soon

**Comment by christiaangoossens** [comment]
I am also a bit stuck on this, especially with the kube-vip CCM, https://kube-vip.io/docs/usage/cloud-provider/

If I have a dual stack cluster, and a CIDR for IPv4 and one for IPv6 to announce in (with ARP and NDP), how should I configure kube-vip (both the DaemonSet and CCM configmap) to deal with DualStack services?

Would it be possible to add a page to the documentation for dual stack use? The only mention of IPv6 I could find was in the features page.

**Comment by jjschwarz** [comment]
Do you know what build version this PR is being included in?

**Comment by aep** [comment]
just doing two single stack lbs for v4 and v6 works for me.

**Comment by jjschwarz** [comment]
Are you doing the single stack in the new v0.70 build?  I was doing this prior to that.

**Comment by lubronzhan** [comment]
Now with kubevip 0.7  and kubevip-lb 0.0.9, dual stack on single service should work. The feature was just added

**Comment by jjschwarz** [comment]
I need to redo my setup to try that.  Are you aware of any documentation on the changes in the manifest creation process?
The documentation at https://kube-vip.io/docs/installation/static/ still seems to have just the single VIP value still, but the 
page at https://kube-vip.io/docs/installation/flags/ shows that as deprecated.  I assume using the --address twice (once for
IPv4 and once for IPv6) will work?

**Comment by lubronzhan** [comment]
For control plane HA it's still single stack, it just add dual stack support for load balancer type service https://github.com/kube-vip/kube-vip/pull/687

**Comment by lubronzhan** [comment]
Rereading the PR and its test, I think it does add support to advertise both ipv4 and ipv6 ip for control plane endpoint.

https://github.com/kube-vip/kube-vip/pull/722

But I'm curious how it works with kubeadm and other k8s bootstraper, I guess you need to tell them to sign the certificate with both IPs for control plane endpoint

**Comment by jjschwarz** [comment]
That is how I am setup now, but with two instances of kubevip.  Just struggling to find clean documentation of how to do that with the change.

**Comment by lubronzhan** [comment]
We can add document. For now you can try just use single kube-vip instance, and input both ipv4, ipv6 in the kube-vip manifest where you used to put your single control plane vip, for example
```
name: address
value: 192.168.254.80
```

Change to 
```
name: address
value: 192.168.254.80,fd::0:1
```

**Comment by jjschwarz** [comment]
OK, so still not solving my issue yet.

**Comment by Cellebyte** [comment]
What exactly is your issue? You could still run 2 Kube-vip instances until it gets implemented.

**Comment by jjschwarz** [comment]
That is what I am doing right now...however since I have one for IPv4 and one for IPv6 I find the IPv4 one is advertising services for both stacks.
In my case that works, but sometimes causes interesting issues tracing down issues because sometimes different nodes are the IPv4 and IPv6
masters.

**Comment by lubronzhan** [comment]
Hi @Cellebyte, the [PR's](https://github.com/kube-vip/kube-vip/pull/722) title mentioned it only adds dual stack for service type LB, but the code itself already supports dual stack VIPs for control plane endpoint from what I see. You can see here

Now it will parse multiple address from `c.VIP` field split by `,` https://github.com/kube-vip/kube-vip/pull/722/files#diff-f4933755bd63c9e160a2068e8ccb4048e8df1b43f7f4544dcbc7ae2650a07478R42-R60. Then the VIPs gathered in this func are used by [singleNode](https://github.com/kube-vip/kube-vip/pull/722/files#diff-86d8461d5aa299f9901bfcc6bdedbd8578080d3f0571b28f09428233f7fda94cR26-R58) and [vipservices](https://github.com/kube-vip/kube-vip/pull/722/files#diff-86d8461d5aa299f9901bfcc6bdedbd8578080d3f0571b28f09428233f7fda94cR26-R58) which called by `ClusterLeaderElection`

And also in his E2E test he already added test that will input both ipv4 and ipv6 addresses for control plane endpoint and it pass https://github.com/kube-vip/kube-vip/pull/722/files#diff-436592853c137f2a8273f91d77df8ca74d8fbdb52046bde9637db6bd78ce0826R317-R321

I know he didn't mention it in his PR but looks like he accidently implements it when implement for service type LB. Please correct me if I'm wrong.

So when you generate manifest for kube-vip, you can do
```
@./kube-vip manifest daemonset --interface eth0 --vip 192.168.0.1
```

```
@./kube-vip manifest daemonset --interface eth0 --vip 192.168.0.1,fd:00:1
```

**Comment by Cellebyte** [comment]
@lubronzhan do you still see an issue here with the latest 0.8.0 release?

**Comment by jjschwarz** [comment]
Afraid I have not been able to test it out yet, but I have that on the schedule for next week.

**Comment by lubronzhan** [comment]
Hi @Cellebyte, I didn't have the chance to test it out, will leave it to @jjschwarz.

**Comment by M0NsTeRRR** [comment]
Hello,

Just tested it appears to works fine :)

tcpdump ipv6
```
$ tcpdump -t -n -vvv -i enp6s18 icmp6
tcpdump: listening on enp6s18, link-type EN10MB (Ethernet), snapshot length 262144 bytes
IP6 (flowlabel 0x9707b, hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::be24:11ff:fe0d:101f > ff02::1: [icmp6 sum ok] ICMP6, neighbor advertisement, length 32, tgt is 2a0c:b641:2c0:110::80, Flags [override]
          destination link-address option (2), length 8 (1): bc:24:11:0d:10:1f
            0x0000:  bc24 110d 101f
```

tcpdump ipv4
```
$ tcpdump -t -n -vvv -i enp6s18 arp
tcpdump: listening on enp6s18, link-type EN10MB (Ethernet), snapshot length 262144 bytes
ARP, Ethernet (len 6), IPv4 (len 4), Reply 192.168.10.80 is-at bc:24:11:0d:10:1f, length 28
```

curl ipv6
```
$ curl https://[2a0c:b641:2c0:110::80]:6443 -k
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

curl ipv4
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Comment by lubronzhan** [comment]
That's good news! We should update our doc

**Comment by Cellebyte** [comment]
@lubronzhan @M0NsTeRRR @jjschwarz do you agree then on closing this issue?

**Comment by jjschwarz** [comment]
His test looks like what I would expect.  If I see any additional issues I can always open a new case after we do our upgrades next week.

**Comment by Cellebyte** [comment]
Closed ;)
