### ISSUE TITLE
Re-write load-balancer to take advantage of know control-plane members

### ISSUE THREAD

**Issue by thebsdbox** [kube-vip/kube-vip#66]
At the moment with the change to `leaderElection` we're mainly focussed on just providing VIP services. It would be good to investigate if we can grab all `controlPlane` members regularly and use this as the backend array for load-balancing.

**Comment by dhawal55** [comment]
Would it be possible to forward traffic received at the VIP to the Kubernetes service IP? Kube-proxy can that take care of load balancing to all API server instances

**Comment by thebsdbox** [comment]
This is for the control-plane, the TCP traffic for the load-balancers is out of cluster so would never go to the `kube-proxy`

**Comment by dhawal55** [comment]
yes, I'm talking about the control plane. Once the traffic reaches the VIP (which is a kube-vip pod running on controlPlane node), we can have an ip-table rule forward the traffic to the internal kubernetes service IP.

**Comment by thebsdbox** [comment]
I'll build a cluster over the coming days and see what I need to do

Notes: 
https://stackoverflow.com/questions/60100233/k8s-forwarding-from-public-vip-to-clusterip-with-iptables
