### ISSUE TITLE
Multiple Raspberry Pis as master nodes do not work without extra configuration

### ISSUE THREAD

**Issue by lazar-boradzhiev** [kube-vip/kube-vip#663]
**Describe the bug**
This is sort of a nit-picky situation, but decided it might be at least worth documenting somewhere, because I didn't find information. I recently installed kube vip on two raspberry pi 4 running the Raspbian Lite OS. As soon as I configured them both as master nodes the connection to the control plane became very flacky and was dropping every few seconds. I got the following message in the logs:
```
1 leaderelection.go:364] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "plndr-cp-lock": the object has been modified; please apply your changes to the latest version and try again
```

So I started digging and found out that the ids that are used are conflicting. Then I took a look at how an ids is generated and according to this piece of code it's using the hostname of the machine:
 https://github.com/kube-vip/kube-vip/blob/main/pkg/cluster/clusterLeaderElection.go#L79.
 `id, err := os.Hostname()`
 
By default the Raspbian hostname is `raspberrypi`, so this caused both kube-vip instances to report the same id. After changing the hostname on both raspberries the problem was resolved.

**To Reproduce**
1. Install and configure 2 raspbian master nodes
2. Install and configure kube-vip to run on the two nodes

**Expected behavior**
I expected the kube vip to run with fewer manual interventions or at least have documented that the hostname should be unique for every master node.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Raspberry Pi OS Lite 64bit October 10th 2023
 - Kubernetes Version: K3s v1.27.7+k3s2
 - Kube-vip Version: v0.6.3

**Kube-vip.yaml:**
If Possible add in your kube-vip manifest (please remove anything that is confidential)

**Additional context**

**Comment by thebsdbox** [comment]
The Kubernetes control plane requires a minimum of 3 nodes in order for quorum and leaderElections to take place.
