### ISSUE TITLE
Does kube-vip Work with VPN Environments like Wireguard?

### ISSUE THREAD

**Issue by backslash112** [kube-vip/kube-vip#667]
My understanding is that kube-vip might not be fully compatible with VPNs like Wireguard, since it binds IP addresses to MAC addresses. I’m reaching out to confirm whether this is the case. Any insights or clarifications on this matter would be greatly appreciated.

**Comment by thebsdbox** [comment]
Kube-vip support wireguard directly, closing this for now.
