### ISSUE TITLE
UDP Not Working

### ISSUE THREAD

**Issue by Ashkaan** [kube-vip/kube-vip#691]
**Describe the bug**
None of my services on UDP ports are working.  TCP is perfect.

**To Reproduce**
Configure a Service like this one:

`apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: omada-controller
  labels:
    app.kubernetes.io/instance: omada-controller
    app.kubernetes.io/name: omada-controller
  annotations:
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.112
  ports:
  - port: 8043
    targetPort: 8043
    protocol: TCP
    name: https
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  - port: 8843
    targetPort: 8843
    protocol: TCP
    name: unknown
  - port: 27001
    targetPort: 27001
    protocol: UDP
    name: app-discovery
  - port: 29810
    targetPort: 29810
    protocol: UDP
    name: port-discovery
  - port: 29811
    targetPort: 29811
    protocol: TCP
    name: manager-v1
  - port: 29812
    targetPort: 29812
    protocol: TCP
    name: adopt-v1
  - port: 29813
    targetPort: 29813
    protocol: TCP
    name: upgrade
  - port: 29814
    targetPort: 29814
    protocol: TCP
    name: manager-v2
  - port: 29815
    targetPort: 29815
    protocol: TCP
    name: transfer
  - port: 29816
    targetPort: 29816
    protocol: TCP
    name: rtty
  selector:
    app.kubernetes.io/instance: omada-controller
    app.kubernetes.io/name: omada-controller`

**Expected behavior**
I would expect that connects on those ports work.  TCP works perfectly.  I've also tried a UDP only Service to rule out a mixed issue.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.0.4.03
 - Kubernetes Version: 1.28.4+k3s2
 - Kube-vip Version: v0.6.4

**`Kube-vip.yaml`:**
`apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: kube-vip-ds
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: eth0
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: 10.1.0.101
        - name: prometheus_server
          value: :2112
        image: ghcr.io/kube-vip/kube-vip:v0.6.4
        imagePullPolicy: Always
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0`

**Additional context**
In my previous cluster, this worked great with MetalLB (but I like kube-vip more).

**Comment by Ashkaan** [comment]
omg.. the formatting is all messed up

**Comment by Ashkaan** [comment]
Service: https://pastebin.com/raw/nGhLsqv8
Kube-VIP: https://pastebin.com/raw/JgqCd4Cw

**Comment by Cellebyte** [comment]
Should work with the latest version.
