### ISSUE TITLE
kube-vip not doing LB

### ISSUE THREAD

**Issue by korenlev** [kube-vip/kube-vip#705]
**To Reproduce**
install
test which node is chosen on incoming traffic
validate that 100% of the times (at stable state) traffic hit leader node only (default election to all services)

leader-election set to "per service":
per k8s choice for pod/service placement traffic may (or may not!) hit a different node but 100% of the times (at stable state) only that specific single node.

BGP use-case with IPVS:
same incoming (single) node is chosen based on current available upstream route

**Expected behavior**
kube-vip claim to be a LoadBalancer (not just HA), expected it to load balance incoming traffic

**Questions**
1. can one set kube-vip to real LB ? any LB algorithms might be supported ?
2. does it rely on other systems on the leader node (like kube-proxy or others) to do internal LB?
3. in case 2. is true - is it true that the only node client connect to from outside the cluster (in stable state) is the leader node ?

**Comment by thebsdbox** [comment]
The larger problem really here is with the terminology attached to Kubernetes services themselves, the "load balancing" is applied by `kube-proxy` within the cluster. Additionally we're providing load-balancing to the Control plane.  Closing this as stale for now.
