### ISSUE TITLE
VIP ARP changes node InternalIP causing log calls to fail

### ISSUE THREAD

**Issue by aidapsibr** [kube-vip/kube-vip#741]
**Describe the bug**

When kube-vip advertises on eth0 (only interface) it replaces the node InternalIP in the Kubernetes API. When trying to use node-level api calls like getting logs will attempt to use the VIP address, but the certificate doesn't have all possible VIPs as SANs.

I have 4 nodes 192.168.163.11-14 and use 192.168.163.10 as the control plane VIP.

 ~/ kubectl logs vmsingle-ephemeral-5787ccbc46-6t4vd --namespace vm
Error from server: Get "https://192.168.163.10:10250/containerLogs/vm/vmsingle-ephemeral-5787ccbc46-6t4vd/vmsingle": tls: failed to verify certificate: x509: certificate is valid for 192.168.163.13, fde0:82bc:37c1, 2002:4bac:30 not 192.168.163.10

**To Reproduce**
- Setup microk8s with launch configuration to add extraSANs set to VIP (192.168.163.10)
- Deploy kube-vip with control plane set to 192.168.163.10 
- Confirm API login and calls work as expected
- Notice whichever node was elected as leader now has node InternalIP set to VIP
- Try to view logs in that node

**Expected behavior**
Node InternalIP not overwritten from host IP

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Ubuntu 22.04
 - Kubernetes Version: v.1.29
 - Kube-vip Version: 0.6.4

**`Kube-vip.yaml`:**

address : 192.168.163.10
cp_enable : true
cp_namespace : kube-system
port : 6443
prometheus_server : :2112
svc_election : true
svc_enable : true
svc_leasename : plndr-svcs-lock
vip_arp : true
vip_cidr : 32
vip_ddns : false
vip_leaderelection : true
vip_leaseduration : 5
vip_leasename : plndr-cp-lock
vip_renewdeadline : 3
vip_retryperiod : 1

**Comment by aidapsibr** [comment]
I found that the problem is with default behavior in kubelet. If you do not specify a node-ip, it will attempt to observe the IP on the primary network interface. Surprisingly, this occurs over time and not just at start-up it seems. This makes the ARP path similar to having 2 interfaces on a node competing. The fix was to speciffy additional Kubelet args to set node-ip to eth0 assigned address.

See this helpful post about the 2 interfaces issue.
https://medium.com/@kanrangsan/how-to-specify-internal-ip-for-kubernetes-worker-node-24790b2884fd

I feel the docs should be updated on the ARP behavior to caution on this.

**Comment by thebsdbox** [comment]
The docs are free to update, but I can update them too. Let me know.

**Comment by linsite** [comment]
@aidapsibr the doc has updated.
