### ISSUE TITLE
No automatic failover when control-plane with the VIP goes down in ARP mode.

### ISSUE THREAD

**Issue by ckazimie** [kube-vip/kube-vip#748]
**Describe the bug**
In a claster consisting of 2 master nodes/control-planes, there was no automatic failover when control-plane with the VIP went down in the ARP mode. The remaining node could not acquire the plndr-cp-lock:

~~~log
2024-01-10T00:16:21.583968654+01:00 stderr F E0109 23:16:21.581864       1 leaderelection.go:367] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "plndr-cp-lock": the object has been modified; please apply your changes to the latest version and try again
~~~

If this is the expected situation due to the leader election is there any manual procedure to select the remaining node as the leader in the cluster? 

**To Reproduce**
In a cluster consiting of two control-planes with kube-vip running in ARP node, shut down the current leader, the holder of VIP. 

**Expected behavior**
The remaining control-place is assuming the leader role automatically or there is a manual procedure to appoint the remaining node as the leader. 

**Environment (please complete the following information):**
 - OS/Distro:  RHEL 8.9
 - Kubernetes Version: 1.26 with cri-o
 - Kube-vip Version: 0.4.4

**`Kube-vip.yaml`:**

~~~yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_interface
      value: ens140
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 172.28.62.133
    image: ghcr.io/kube-vip/kube-vip:v0.4.4
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
~~~

**Comment by thebsdbox** [comment]
Yeah, without a HA `etcd` we can't provide HA for the control plane. This is a Kubernetes requirement of the project itself.

**Comment by McTrk** [comment]
The issue can be reproduced with a three-node stacked cluster, by deleting the node with the VIP.

**Comment by csakaszamok** [comment]
Same issue is with 3 masters

**Comment by lubronzhan** [comment]
Could you upload logs of all kube-vip pods in this case and reopen a new issue when the issue happens?
