### ISSUE TITLE
Select kube-vip instance by LoadalancerClass

### ISSUE THREAD

**Issue by pasztorl** [kube-vip/kube-vip#791]
I'm using two instances for the private/public interfaces. Currently I'm deployed them to separate namespaces and they listening their namespace only.

Now I have more namespace which needed vip, but this config will not handle it. I found the ticket about the LoadbalancerClass, It now restrict kube-vip to one label key.  https://github.com/kube-vip/kube-vip/issues/413 witch not far to solve this problem.

If the label not static, but configurable via env I can deploy multiple kube-vip checking all namespaces but the instances restricted to their configured LoadbalancerClass. I think this can be more flexible/useable.

**Comment by angeloxx** [comment]
+1, but you have also to change add a parameter to set the lease name, because the kubevip instance uses a standard name (plndr-svcs-lock) for all instances.

**Comment by Cellebyte** [comment]
Should all be doable with the latest kube-vip version and 2 separate darmonsets using different LoadbalancerClasses.
