### ISSUE TITLE
kube-vip remove all ip address on the eth device

### ISSUE THREAD

**Issue by maitredede** [kube-vip/kube-vip#798]
**Describe the bug**
I have a small k3s cluster : 3 master Rpi4 (raspberry pi OS bookworm 64), connected on ethernet (ip are DHCP static). When installing kube-vip as daemonset, the vip is set, and after a few minutes, there is no longer any ip on the device.
It is hard to get kube-vip logs since when a node is isolated (no ip address), k3s drops its sockets, and crictl no longer works.
If I add manually the ip (ip addr...) and the default route, I can restart k3s, but when corum is available (2 nodes on 3), ip are removed again (a few  moment later). All the ip are 192.168.20.xxx/24 : vip is .200, dhcp nodes are 201, 202, 203

I tried many options, but I don't know why either the DHCP address has netmask updated from 24 to 32, why VIP has netmask of 32, why all addresses are removed... I don't understand how options acts on final addresses and netmasks...

**To Reproduce**
1. Install kube-vip as daemonset
2. Wait a few minutes
3. All nodes have lost their DHCP address

**Expected behavior**
IP given by DHCP should be kept intact and VIP should have same netmask to work properly. Also routes should not be altered since they are on same network.

**Environment (please complete the following information):**
 - OS/Distro: Raspberry Pi OS lite bookworm arm64
 - Kubernetes Version: k3s stable v1.28.8+k3s1
 - Kube-vip Version: v0.7.2

**`Kube-vip.yaml`:**
```yaml
docker run --network host --rm ghcr.io/kube-vip/kube-vip:$KVVERSION manifest daemonset \
    --interface eth0 \
    --vip 192.168.20.200 \
    --vipSubnet "/24" \
    --cidr 24 \
    --inCluster \
    --taint \
    --controlplane \
    --services \
    --servicesElection \
    --arp \
    --leaderElection
    ```

**Comment by MartinLoeper** [comment]
Observed exactly the same on a tinkerbell k3s setup in my homelab (since tinkerbell uses kube-vip). Extremely difficult to debug...

**Comment by Cellebyte** [comment]
For ARP mode the interface auto discovery and cidr auto discovery was added. Maybe you give it a try with the latest live-vip.
