### ISSUE TITLE
Better support for offline deployment

### ISSUE THREAD

**Issue by Bao0ne** [kube-vip/kube-vip#804]
When using kube-vip when deploying k3s offline, I found that the ImagePullPolicy in the kubevip.yaml generated by the kube-vip cli was hardcoded to Always. Are there any other considerations?

Maybe IfNotPresent has better compatibility

https://github.com/kube-vip/kube-vip/blob/f1cf044eae1edcb016b3aab10480038c423a0fdb/pkg/kubevip/config_generator.go#L539

**Comment by lubronzhan** [comment]
I agree `IfNotPresent` makes more sense and more widely used 
Would you mind creating a PR to change that
