### ISSUE TITLE
Allow vip_interface to be set on a per-node basis using node labels or annotations

### ISSUE THREAD

**Issue by e3b0c442** [kube-vip/kube-vip#822]
**Is your feature request related to a problem? Please describe.**
When using Layer 2/ARP mode with daemonsets, the VIP interface must be the same on all hosts. This breaks in even moderately heterogenous environments. The current solution is to either use static pods on the individual node kubelets, or use udev rules to rename the interfaces on individual nodes. These are both potentially undesirable.

**Describe the solution you'd like**
An annotation or label placed on a node, e.g. `kube-vip.io/vip-interaface=enp1s0` which informs kube-vip which interface should advertise ARP. When set, this annotation/label would override the configuration parameter.

**Describe alternatives you've considered**
Using static pods or renaming interfaces on nodes as described above

**Comment by thebsdbox** [comment]
https://github.com/kube-vip/kube-vip/releases/tag/v0.8.0 - this was literally added yesterday 😀

**Comment by e3b0c442** [comment]
Is it? I saw this and it's what prompted me to create this issue.

As documented, that seems like an annotation that goes on a service, which wouldn't be node-specific. It also wouldn't apply to control-plane HA. A reading of the code seems to confirm that. If that's not the case, there may be some clarification needed on how to apply that annotation to specific nodes.

**Comment by thebsdbox** [comment]
This is for services not the control plane, for the control plane it's typically static pod manifests, but kube-vip can also autodetect the interface based upon the default route.

**Comment by chenyuanrun** [comment]
I want this feature too, I have totally different nodes in my k8s cluster and the name (and type) of interfaces in those nodes is different. I hope kube-vip can choose the interface for vip per node AND per service.

For example, I can set the vip in nodeA to eno2, and if the vip change to nodeB, it is set to eno3.

**Comment by chenyuanrun** [comment]
@thebsdbox Maybe we can add a configmap to override the default interface selection. kube-vip can choose interface from:
- kube-vip global configuration;
- per service configuration;
- config map for the service;

and we can save something in the configmap just like:
```yaml
- name: nodeA
  interface: eno2
- name: nodeB
  interface: eno3
```

**Comment by e3b0c442** [comment]
I had started to respond to this and got waylaid and forgot about it...

I begin to wonder if the DaemonSet mode of operation should be deprecated?

The documentation mentions upsides of running as a DaemonSet vs static pods, but does kube-vip actually take advantage of those? Seems to me that because there are use cases where DaemonSet just simply cannot work that we are forced into a lower common denominator. 

Barring that, I do believe a label or annotation on the node for this makes sense, because there are absolutely cases where the inferred default is not the desired interface. I think it's cleaner -- since the delineation would be node-based -- than needing to have another object in the cluster just for this configuration item. 

I'm working on getting authorization to contribute code to some CNCF projects, if I can secure that maybe I can find some time to take a crack at this.

**Comment by mishun** [comment]
I was looking if that's possible today. It would be nice to have this feature.

**Comment by Cellebyte** [comment]
The `auto` mode is currently possible.
And this annotation https://github.com/kube-vip/kube-vip/blob/18544a5d5467834c10e4a3bd8f753aaab211dd71/pkg/kubevip/annotations.go#L53
