### ISSUE TITLE
Support table mode for CP mode

### ISSUE THREAD

**Issue by MaxRink** [kube-vip/kube-vip#831]
**Is your feature request related to a problem? Please describe.**
Currently only BGP, APR and WG modes are implemented for the CP mode.

**Describe the solution you'd like**
We would like to have the table mode with an healthcheck of the local API-Server on each node, so that we can utilize ECMP Load Balancing for the API-Server

**Comment by thebsdbox** [comment]
Makes sense, I don't think it would be a large amount of effort... all the functions are there, they just need wiring together! 🔌

**Comment by Cellebyte** [comment]
Done
