### ISSUE TITLE
Default value of vip_cidr

### ISSUE THREAD

**Issue by M0NsTeRRR** [kube-vip/kube-vip#852]
**Is your feature request related to a problem? Please describe.**
If you set an IP with `--vip` flag, vip_cidr default to `32` even if it's an IPv6.

**Describe the solution you'd like**
Remove the default value and instead, at runtime, if no values are passed, set the value to `32` for IPv4 and `128` for IPv6. Ensure it can handle multiple IPs as well following #631.

I've looked into the code and it says that the flag is deprecated from a PR regarding routing table but I don't know why.
If it's not deprecated and you agree with the idea, I can create the associated PR :).

**Comment by thebsdbox** [comment]
It's time for my favourite catchphrase!

"PRs welcome 🎉"

But in seriousness, that would be great 😄

**Comment by M0NsTeRRR** [comment]
Just wanted to know if this option is still deprecated before doing it to avoid useless works.

Deprecated message is here : https://github.com/kube-vip/kube-vip/blob/e9835aa9817e378b793e9d4ba3699322225090f1/cmd/kube-vip.go#L63
