### ISSUE TITLE
How to set vip for pods with hostNetwork

### ISSUE THREAD

**Issue by chenyuanrun** [kube-vip/kube-vip#870]
**Is your feature request related to a problem? Please describe.**

I have a deployment with 1 pod who export its service via hostNetwork (kernel module export the port in fact). I need to access this service via a VIP without define a service (as the port is accessable via hostNetwork), but it seems kube-vip need a service of LoadBalance to attach a vip.

**Describe the solution you'd like**

Support attach vip to the node for my pod without define a new service.

**Describe alternatives you've considered**
Define a service and map a useless port to my host port.

**Additional context**
NO.

**Comment by Cellebyte** [comment]
Maybe you define an empty service with handcrafted endpoints.
