### ISSUE TITLE
Upgrading Service Only Manifest Generation for K3S from 0.6.2 to 0.81 results in "invalid IP address"

### ISSUE THREAD

**Issue by jjschwarz** [kube-vip/kube-vip#885]
**Describe the bug**
I had a script to generate a service only setup for K3S that was put in a manifest.  The command for v0.6.2 was functioning fine, however under 0.8.1 it results in "invalid IP address: ".

**To Reproduce**
Run the command:
sudo ctr run --net-host --rm ghcr.io/kube-vip/kube-vip:v0.8.1 vip /kube-vip manifest daemonset \
--interface eth0 \
--inCluster \
--taint \
--services \
--lbClassOnly \
--arp \
--leaderElection

**Expected behavior**
Generates service only manifest as it did in v0.6.2

**Environment (please complete the following information):**
 - OS/Distro: Debian GNU/Linux 10 (buster)
 - Kubernetes Version: k3s v1.27.9
 - Kube-vip Version: 0.8.1

**Additional context**
I may (likely) be missing a configuration changes in the manifest generation, but I do not see anything obvious.

**Comment by thebsdbox** [comment]
Well this is embarrassing, we must be missing some tests here.

**Comment by thebsdbox** [comment]
I’ll fix this hopefully tomorrow and drop another release.

**Comment by jjschwarz** [comment]
This appears to have been fixed in case 894 and my testing shows it works fine now.

Thank you
