### ISSUE TITLE
v0.8.1 doesn't set vip_cidr default

### ISSUE THREAD

**Issue by bolsblue** [kube-vip/kube-vip#891]
**Describe the bug**
v0.8.1 doesn't set vip_cidr env to 32 on IPv4 cluster by default
Errors show up complaining about invalid CIDR address (ex. "192.168.10.122/" <- missing 32 here), BGP connections don't establish

**To Reproduce**
1. don't set vip_cidr environment variable
2. upgrade to v0.8.1
3. See logs with invalid CIDR errors

**Expected behavior**
CIDR of 32 being set by default

**Environment (please complete the following information):**
 - OS/Distro: Fedora CoreOS 40.20240602.3.0
 - Kubernetes Version: v1.30.2+k3s1
 - Kube-vip Version: v0.8.1

**Additional context**
Seems like it was introduced here:
https://github.com/kube-vip/kube-vip/pull/853

**Comment by cprivitere** [comment]
I think there's a relation of some sort to #885 as the change to fix that also checks the vip_cidr status. And you can avoid 885 entirely by adding --cidr 32 to the manifest command

**Comment by bolsblue** [comment]
To be clear, generating the manifest via `kube-vip manifest` does work as intended.
It's just that I manually created my manifest some time ago and found that it wasn't working anymore after upgrading to v0.8.1.
The release notes didn't indicate this as a breaking change and the [docs](https://kube-vip.io/docs/installation/flags/) still mention that `--cidr` and `vip_cidr` env defaults to 32, which isn't true anymore after https://github.com/kube-vip/kube-vip/pull/853.
This should be updated.

**Comment by M0NsTeRRR** [comment]
Hello,

Yes, I completely forgot to update the associated code (to run kube-vip). The documentation should not mention a breaking change as it's an enhancement (a buggy one for sure).
I will try to look into it tonight. It should be a minor fix; we just have to call `generateCidrRange` if no environment/flag value is set.
I will update the documentation too, good catch !
