### ISSUE TITLE
Design question for control plane HA and Services HA

### ISSUE THREAD

**Issue by philuxe** [kube-vip/kube-vip#914]
Hi all,

I'm wondering how I can achieve both Control Plane and Services HA with kubevip knowing I dont want traffic to services flowing via control plan nodes. The doc was not 100% clear to me on this.

I have a 5 nodes cluster (baremetal) with 3 cp and 2 workers nodes. I have installed kubevip as a static pod and was able to get Control Plane HA. Problem is any traffic going to Loadbalancer services goes via tha control plane which I would like to avoid for permformance and control plan protection reasons.

Should I install another kubevip instance as daemon set for this purpose ? how both kubevip instances (static pod + DS) will coexist ?

Or Should I have static pods on worker nodes too ?

**Comment by Cellebyte** [comment]
Could you open a discussion topic instead of an issue? Just copy your question.
