### ISSUE TITLE
kubernetes api does not respond when kube-vip leader is rebooted with `lb_enable` true

### ISSUE THREAD

**Issue by elijahchanakira** [kube-vip/kube-vip#941]
**Describe the bug**
Kube-vip load balancer is not working as intended in a two control node setup. When I reboot the leader, I am unable to access (curl) the the kubernetes api even though the second control node has kube-vip running. The second control node fails to be promoted to the leader.

**To Reproduce**
1. Launch kube-vip on both nodes, using the yaml shared below
2. Wait for leader to be elected
3. Reboot the leader

The kubernetes api becomes inaccessible for the entirety of the leader's reboot.
**Expected behavior**
I expect the second control plane node to be promoted to leader and for the kubernetes api to become accessible again while the first control plane node is promoted.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: `Ubuntu LTS 22.04`
 - Kubernetes Version:` v1.30`
 - Kube-vip Version: `v0.8.2`

**`Kube-vip.yaml`:**
```apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: port
      value: "6443"
    - name: vip_nodename
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: vip_interface
      value: eth0
    - name: vip_cidr
      value: "32"
    - name: dns_mode
      value: first
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: svc_enable
      value: "true"
    - name: svc_leasename
      value: plndr-svcs-lock
    - name: vip_leaderelection
      value: "true"
    - name: vip_leasename
      value: plndr-cp-lock
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: address
      value: 192.168.40.200
    - name: prometheus_server
      value: :2112
    image: ghcr.io/kube-vip/kube-vip:v0.8.2
    imagePullPolicy: IfNotPresent
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/super-admin.conf
    name: kubeconfig
status: {}
```

**Comment by thebsdbox** [comment]
**two control node setup** - For HA, minimum requirement is three nodes as per the Kubernetes documentation.

**Comment by elijahchanakira** [comment]
@thebsdbox Can we reopen this? the same issue happens with three control plane nodes. Additionally, how would this impact kube-vip's ability to elect a new leader?

**Comment by thebsdbox** [comment]
Because `etcd` won't work with just two nodes. There aren't enough nodes to for etcd to select a new leader, the raft algorithm won't work so the entire API server/Kubernetes will be broken and this is all part of the Kubernetes documentation. If you have logs that show that something is broken in kube-vip for a three node cluster then please attach them and we'll go from there.
